INSERT INTO public.artists ("Artist_ID", "Artist_Name") VALUES (0, 'Gorillaz');
INSERT INTO public.artists ("Artist_ID", "Artist_Name") VALUES (1, 'Rick Astley');
INSERT INTO public.artists ("Artist_ID", "Artist_Name") VALUES (3, 'Darude');
INSERT INTO public.artists ("Artist_ID", "Artist_Name") VALUES (4, 'Discord');
INSERT INTO public.artists ("Artist_ID", "Artist_Name") VALUES (5, 'Smash Mouth');
INSERT INTO public.artists ("Artist_ID", "Artist_Name") VALUES (6, 'Foster The People');
INSERT INTO public.artists ("Artist_ID", "Artist_Name") VALUES (9, 'Getter Jaani');
INSERT INTO public.artists ("Artist_ID", "Artist_Name") VALUES (10, 'Caramella Girls');
INSERT INTO public.artists ("Artist_ID", "Artist_Name") VALUES (11, 'ACE');
INSERT INTO public.artists ("Artist_ID", "Artist_Name") VALUES (12, 'Avril Lavigne');
INSERT INTO public.artists ("Artist_ID", "Artist_Name") VALUES (13, 'Green Day');
INSERT INTO public.artists ("Artist_ID", "Artist_Name") VALUES (14, 'Yes');
INSERT INTO public.artists ("Artist_ID", "Artist_Name") VALUES (2, 'Toby Fox');
INSERT INTO public.artists ("Artist_ID", "Artist_Name") VALUES (7, 'a-ha');
