INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Bite Me', 3, 28, 12, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Love Sux', 3, 30, 12, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Bois Lie', 3, 27, 12, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Tomorrow', 2, 24, 12, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Im With You', 2, 21, 12, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Cannonball', 3, 26, 12, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Unwanted', 2, 23, 12, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Sk8er Boi', 2, 20, 12, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Megalovania', 11, 2, 2, 2000000000);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Feel Good Inc', 5, 0, 0, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('St Jimmy', 4, 36, 14, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Holiday', 4, 33, 14, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Anything But Ordinary', 2, 25, 12, 1);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Time To Fight!', 1, 12, 11, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Are We the Waiting', 4, 35, 14, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Jesus of Suburbia', 4, 32, 14, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('American Idiot', 4, 31, 14, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Boulevard of Broken Dreams', 4, 34, 14, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Discord Ping', 12, 4, 4, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Rockefeller Street', 13, 9, 9, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Pumped Up Kicks', 6, 6, 6, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Take On Me', 14, 7, 7, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Colony 9', 1, 11, 11, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('An Obstacle in Our Way', 1, 15, 11, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Losing Grip', 2, 18, 12, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Complicated', 2, 19, 12, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('All Star', 10, 5, 5, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Never Gonna Give You Up', 7, 1, 1, 162789010);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Frontier Village', 1, 16, 11, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('You Will Know Our Names', 1, 17, 11, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Gaur Plain', 1, 14, 11, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Engage the Enemy', 1, 13, 11, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Give Me Novacaine', 4, 37, 14, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Roundabout', 9, 8, 14, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Mobile', 2, 22, 12, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Caramelldansen', 8, 10, 10, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Shes a Rebel', 4, 38, 14, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Love It When You Hate Me', 3, 29, 12, 0);
INSERT INTO public.songs ("Song_Name", "Album_ID", "Song_ID", "Artist_ID", "Listens") VALUES ('Sandstorm', 15, 3, 3, 96);
