UPDATE public.songs SET "Song_Name" = 'Bite Me', "Album_ID" = 3, "Artist_ID" = 12, "Listens" = 0 WHERE "Song_ID" = 28;
UPDATE public.songs SET "Song_Name" = 'Love Sux', "Album_ID" = 3, "Artist_ID" = 12, "Listens" = 0 WHERE "Song_ID" = 30;
UPDATE public.songs SET "Song_Name" = 'Bois Lie', "Album_ID" = 3, "Artist_ID" = 12, "Listens" = 0 WHERE "Song_ID" = 27;
UPDATE public.songs SET "Song_Name" = 'Tomorrow', "Album_ID" = 2, "Artist_ID" = 12, "Listens" = 0 WHERE "Song_ID" = 24;
UPDATE public.songs SET "Song_Name" = 'Im With You', "Album_ID" = 2, "Artist_ID" = 12, "Listens" = 0 WHERE "Song_ID" = 21;
UPDATE public.songs SET "Song_Name" = 'Cannonball', "Album_ID" = 3, "Artist_ID" = 12, "Listens" = 0 WHERE "Song_ID" = 26;
UPDATE public.songs SET "Song_Name" = 'Unwanted', "Album_ID" = 2, "Artist_ID" = 12, "Listens" = 0 WHERE "Song_ID" = 23;
UPDATE public.songs SET "Song_Name" = 'Sk8er Boi', "Album_ID" = 2, "Artist_ID" = 12, "Listens" = 0 WHERE "Song_ID" = 20;
UPDATE public.songs SET "Song_Name" = 'Megalovania', "Album_ID" = 11, "Artist_ID" = 2, "Listens" = 2000000000 WHERE "Song_ID" = 2;
UPDATE public.songs SET "Song_Name" = 'Feel Good Inc', "Album_ID" = 5, "Artist_ID" = 0, "Listens" = 0 WHERE "Song_ID" = 0;
UPDATE public.songs SET "Song_Name" = 'St Jimmy', "Album_ID" = 4, "Artist_ID" = 14, "Listens" = 0 WHERE "Song_ID" = 36;
UPDATE public.songs SET "Song_Name" = 'Holiday', "Album_ID" = 4, "Artist_ID" = 14, "Listens" = 0 WHERE "Song_ID" = 33;
UPDATE public.songs SET "Song_Name" = 'Anything But Ordinary', "Album_ID" = 2, "Artist_ID" = 12, "Listens" = 1 WHERE "Song_ID" = 25;
UPDATE public.songs SET "Song_Name" = 'Time To Fight!', "Album_ID" = 1, "Artist_ID" = 11, "Listens" = 0 WHERE "Song_ID" = 12;
UPDATE public.songs SET "Song_Name" = 'Are We the Waiting', "Album_ID" = 4, "Artist_ID" = 14, "Listens" = 0 WHERE "Song_ID" = 35;
UPDATE public.songs SET "Song_Name" = 'Jesus of Suburbia', "Album_ID" = 4, "Artist_ID" = 14, "Listens" = 0 WHERE "Song_ID" = 32;
UPDATE public.songs SET "Song_Name" = 'American Idiot', "Album_ID" = 4, "Artist_ID" = 14, "Listens" = 0 WHERE "Song_ID" = 31;
UPDATE public.songs SET "Song_Name" = 'Boulevard of Broken Dreams', "Album_ID" = 4, "Artist_ID" = 14, "Listens" = 0 WHERE "Song_ID" = 34;
UPDATE public.songs SET "Song_Name" = 'Discord Ping', "Album_ID" = 12, "Artist_ID" = 4, "Listens" = 0 WHERE "Song_ID" = 4;
UPDATE public.songs SET "Song_Name" = 'Rockefeller Street', "Album_ID" = 13, "Artist_ID" = 9, "Listens" = 0 WHERE "Song_ID" = 9;
UPDATE public.songs SET "Song_Name" = 'Pumped Up Kicks', "Album_ID" = 6, "Artist_ID" = 6, "Listens" = 0 WHERE "Song_ID" = 6;
UPDATE public.songs SET "Song_Name" = 'Take On Me', "Album_ID" = 14, "Artist_ID" = 7, "Listens" = 0 WHERE "Song_ID" = 7;
UPDATE public.songs SET "Song_Name" = 'Colony 9', "Album_ID" = 1, "Artist_ID" = 11, "Listens" = 0 WHERE "Song_ID" = 11;
UPDATE public.songs SET "Song_Name" = 'An Obstacle in Our Way', "Album_ID" = 1, "Artist_ID" = 11, "Listens" = 0 WHERE "Song_ID" = 15;
UPDATE public.songs SET "Song_Name" = 'Losing Grip', "Album_ID" = 2, "Artist_ID" = 12, "Listens" = 0 WHERE "Song_ID" = 18;
UPDATE public.songs SET "Song_Name" = 'Complicated', "Album_ID" = 2, "Artist_ID" = 12, "Listens" = 0 WHERE "Song_ID" = 19;
UPDATE public.songs SET "Song_Name" = 'All Star', "Album_ID" = 10, "Artist_ID" = 5, "Listens" = 0 WHERE "Song_ID" = 5;
UPDATE public.songs SET "Song_Name" = 'Never Gonna Give You Up', "Album_ID" = 7, "Artist_ID" = 1, "Listens" = 162789010 WHERE "Song_ID" = 1;
UPDATE public.songs SET "Song_Name" = 'Frontier Village', "Album_ID" = 1, "Artist_ID" = 11, "Listens" = 0 WHERE "Song_ID" = 16;
UPDATE public.songs SET "Song_Name" = 'You Will Know Our Names', "Album_ID" = 1, "Artist_ID" = 11, "Listens" = 0 WHERE "Song_ID" = 17;
UPDATE public.songs SET "Song_Name" = 'Gaur Plain', "Album_ID" = 1, "Artist_ID" = 11, "Listens" = 0 WHERE "Song_ID" = 14;
UPDATE public.songs SET "Song_Name" = 'Engage the Enemy', "Album_ID" = 1, "Artist_ID" = 11, "Listens" = 0 WHERE "Song_ID" = 13;
UPDATE public.songs SET "Song_Name" = 'Give Me Novacaine', "Album_ID" = 4, "Artist_ID" = 14, "Listens" = 0 WHERE "Song_ID" = 37;
UPDATE public.songs SET "Song_Name" = 'Roundabout', "Album_ID" = 9, "Artist_ID" = 14, "Listens" = 0 WHERE "Song_ID" = 8;
UPDATE public.songs SET "Song_Name" = 'Mobile', "Album_ID" = 2, "Artist_ID" = 12, "Listens" = 0 WHERE "Song_ID" = 22;
UPDATE public.songs SET "Song_Name" = 'Caramelldansen', "Album_ID" = 8, "Artist_ID" = 10, "Listens" = 0 WHERE "Song_ID" = 10;
UPDATE public.songs SET "Song_Name" = 'Shes a Rebel', "Album_ID" = 4, "Artist_ID" = 14, "Listens" = 0 WHERE "Song_ID" = 38;
UPDATE public.songs SET "Song_Name" = 'Love It When You Hate Me', "Album_ID" = 3, "Artist_ID" = 12, "Listens" = 0 WHERE "Song_ID" = 29;
UPDATE public.songs SET "Song_Name" = 'Sandstorm', "Album_ID" = 15, "Artist_ID" = 3, "Listens" = 96 WHERE "Song_ID" = 3;
