insert into public.artists (Artist_ID, Artist_Name) values (1, 'Taylor Swift');
insert into public.artists (Artist_ID, Artist_Name) values (2, 'Ed Sheeran');
insert into public.artists (Artist_ID, Artist_Name) values (3, 'Lana Del Rey');
insert into public.artists (Artist_ID, Artist_Name) values (4, '3 Doors Down');
insert into public.artists (Artist_ID, Artist_Name) values (5, 'Linkin Park');
insert into public.artists (Artist_ID, Artist_Name) values (6, 'Nickelback');
insert into public.artists (Artist_ID, Artist_Name) values (7, 'Audioslave');
insert into public.artists (Artist_ID, Artist_Name) values (8, 'Evanescence');
insert into public.artists (Artist_ID, Artist_Name) values (9, 'The White Stripes');
insert into public.artists (Artist_ID, Artist_Name) values (10, 'Fall Out Boy');
insert into public.artists (Artist_ID, Artist_Name) values (11, 'Red Hot Chili Peppers');
insert into public.artists (Artist_ID, Artist_Name) values (12, 'Foo Fighters');
insert into public.artists (Artist_ID, Artist_Name) values (13, 'Disturbed');
insert into public.artists (Artist_ID, Artist_Name) values (14, 'The Offspring');
insert into public.artists (Artist_ID, Artist_Name) values (15, 'Staind');
insert into public.artists (Artist_ID, Artist_Name) values (16, 'Incubus');
insert into public.artists (Artist_ID, Artist_Name) values (17, 'Green Day');
insert into public.artists (Artist_ID, Artist_Name) values (18, 'P.O.D.');
insert into public.artists (Artist_ID, Artist_Name) values (19, 'Shinedown');
insert into public.artists (Artist_ID, Artist_Name) values (20, 'Velvet Revolver');
insert into public.artists (Artist_ID, Artist_Name) values (21, 'Seether');
insert into public.artists (Artist_ID, Artist_Name) values (22, 'Three Days Grace');
insert into public.artists (Artist_ID, Artist_Name) values (23, 'Bon Jovi');
insert into public.artists (Artist_ID, Artist_Name) values (24, 'Coldplay');
insert into public.artists (Artist_ID, Artist_Name) values (25, 'The Killers');
insert into public.artists (Artist_ID, Artist_Name) values (26, 'My Chemical Romance');
insert into public.artists (Artist_ID, Artist_Name) values (27, 'Muse');
insert into public.artists (Artist_ID, Artist_Name) values (28, 'Creed');
insert into public.artists (Artist_ID, Artist_Name) values (29, 'Godsmack');
insert into public.artists (Artist_ID, Artist_Name) values (30, 'Crazy Town');
insert into public.artists (Artist_ID, Artist_Name) values (31, 'U2');
insert into public.artists (Artist_ID, Artist_Name) values (32, 'Jet');
insert into public.artists (Artist_ID, Artist_Name) values (33, 'The Strokes');
insert into public.artists (Artist_ID, Artist_Name) values (34, 'Daughtry');
insert into public.artists (Artist_ID, Artist_Name) values (35, 'Breaking Benjamin');
insert into public.artists (Artist_ID, Artist_Name) values (36, 'Good Charlotte');
insert into public.artists (Artist_ID, Artist_Name) values (37, 'Stone Sour');
insert into public.artists (Artist_ID, Artist_Name) values (38, 'Weezer');
insert into public.artists (Artist_ID, Artist_Name) values (39, 'Aerosmith');
insert into public.artists (Artist_ID, Artist_Name) values (40, 'Yellowcard');
insert into public.artists (Artist_ID, Artist_Name) values (41, 'Lifehouse');
insert into public.artists (Artist_ID, Artist_Name) values (42, 'Ozzy Osbourne');
insert into public.artists (Artist_ID, Artist_Name) values (43, 'Chevelle');
insert into public.artists (Artist_ID, Artist_Name) values (44, 'AC/DC');
insert into public.artists (Artist_ID, Artist_Name) values (45, 'Metallica');
insert into public.artists (Artist_ID, Artist_Name) values (46, 'Jimmy Eat World');
insert into public.artists (Artist_ID, Artist_Name) values (47, 'Puddle of Mudd');
insert into public.artists (Artist_ID, Artist_Name) values (48, 'Simple Plan');
insert into public.artists (Artist_ID, Artist_Name) values (49, 'Our Lady Peace');
insert into public.artists (Artist_ID, Artist_Name) values (50, 'The Raconteurs');
insert into public.artists (Artist_ID, Artist_Name) values (51, 'Pearl Jam');
insert into public.artists (Artist_ID, Artist_Name) values (52, 'Hiroyuki Sawano');
insert into public.artists (Artist_ID, Artist_Name) values (53, '澤野弘之');
insert into public.artists (Artist_ID, Artist_Name) values (54, 'Yuki Kajiura');
insert into public.artists (Artist_ID, Artist_Name) values (55, '梶浦由記');
insert into public.artists (Artist_ID, Artist_Name) values (56, 'BLACKPINK');
insert into public.artists (Artist_ID, Artist_Name) values (57, 'Rina Sawayama');
insert into public.artists (Artist_ID, Artist_Name) values (58, 'Avril Lavigne');
insert into public.artists (Artist_ID, Artist_Name) values (59, 'Billie Eilish');
insert into public.artists (Artist_ID, Artist_Name) values (60, 'Grimes');
insert into public.artists (Artist_ID, Artist_Name) values (61, 'GAYLE');
insert into public.artists (Artist_ID, Artist_Name) values (62, 'Snail Mail');
insert into public.artists (Artist_ID, Artist_Name) values (63, 'St. Vincent');
insert into public.artists (Artist_ID, Artist_Name) values (64, 'The Linda Lindas');
insert into public.artists (Artist_ID, Artist_Name) values (65, 'Wet');
insert into public.artists (Artist_ID, Artist_Name) values (66, 'Hana Vu');
insert into public.artists (Artist_ID, Artist_Name) values (67, 'Wet Leg');
insert into public.artists (Artist_ID, Artist_Name) values (68, 'Lorde');
insert into public.artists (Artist_ID, Artist_Name) values (69, 'Paramore');
insert into public.artists (Artist_ID, Artist_Name) values (70, 'mxmtoon');
insert into public.artists (Artist_ID, Artist_Name) values (71, 'Clairo');
insert into public.artists (Artist_ID, Artist_Name) values (72, 'King Princess');
insert into public.artists (Artist_ID, Artist_Name) values (73, 'K.Flay');
insert into public.artists (Artist_ID, Artist_Name) values (74, 'Amy Shark');
insert into public.artists (Artist_ID, Artist_Name) values (75, 'Phantogram');
insert into public.artists (Artist_ID, Artist_Name) values (76, 'Bishop Briggs');
insert into public.artists (Artist_ID, Artist_Name) values (77, 'HAIM');
insert into public.artists (Artist_ID, Artist_Name) values (78, 'Hayley Williams');
insert into public.artists (Artist_ID, Artist_Name) values (79, 'Sharon Van Etten');
insert into public.artists (Artist_ID, Artist_Name) values (80, 'CHVRCHES');
insert into public.artists (Artist_ID, Artist_Name) values (81, 'PVRIS');
insert into public.artists (Artist_ID, Artist_Name) values (82, 'The Regrettes');
insert into public.artists (Artist_ID, Artist_Name) values (83, 'Alice Merton');
insert into public.artists (Artist_ID, Artist_Name) values (84, 'Wolf Alice');
insert into public.artists (Artist_ID, Artist_Name) values (85, 'Tash Sultana');
insert into public.artists (Artist_ID, Artist_Name) values (86, 'carolesdaughter');
insert into public.artists (Artist_ID, Artist_Name) values (87, 'Pale Waves');
insert into public.artists (Artist_ID, Artist_Name) values (88, 'MisterWives');
insert into public.artists (Artist_ID, Artist_Name) values (89, 'Elle King');
insert into public.artists (Artist_ID, Artist_Name) values (90, 'Mallrat');
insert into public.artists (Artist_ID, Artist_Name) values (91, 'Middle Kids');
insert into public.artists (Artist_ID, Artist_Name) values (92, 'Pom Pom Squad');
insert into public.artists (Artist_ID, Artist_Name) values (93, 'Meg Myers');
insert into public.artists (Artist_ID, Artist_Name) values (94, 'The Aces');
insert into public.artists (Artist_ID, Artist_Name) values (95, 'Charly Bliss');
insert into public.artists (Artist_ID, Artist_Name) values (96, 'Dead Sara');
insert into public.artists (Artist_ID, Artist_Name) values (97, 'Valeras');
insert into public.artists (Artist_ID, Artist_Name) values (98, 'Liz Phair');
