insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Shake It Off', 1, 1, 1, 0, 'nfWlot6h_JM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Wildest Dreams', 1, 2, 1, 0, 'CUr_UwUUXzU');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Blank Space', 1, 4, 1, 0, 'e-ORhEE9VVg');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Style', 1, 5, 1, 0, '-CmadmM5cOk');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Bad Blood', 1, 6, 1, 0, 'QcIy9NiNbmo');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('All Too Well: The Short Film', 2, 7, 1, 0, 'tollGa3S0o8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('You Belong With Me', 3, 8, 1, 0, 'vwp8Ur6tO-8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Love Story', 3, 9, 1, 0, 'aXzVF3XeS8M');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Fifteen', 3, 10, 1, 0, 'rLCol1C3ouc');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('22', 4, 11, 1, 0, '9boiT64sm0Q');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Red', 4, 12, 1, 0, 'R_rUYuFtNO4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('All Too Well', 4, 13, 1, 0, 'F8Jxo15Vfic');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('I Knew You Were Trouble', 5, 14, 1, 0, 'TqAollrUJdA');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Everything Has Changed', 5, 15, 1, 0, 'w1oM3kQpXRo');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('right where you left me', 6, 16, 1, 0, 'Ur_wAcYDnuA');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Cruel Summer', 7, 17, 1, 0, 'ic8j13piAhQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('gold rush', 8, 18, 1, 0, 'Pz-f9mM3Ms8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Run', 9, 19, 1, 0, 'flv8AEWrRMI');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('no body, no crime', 10, 20, 1, 0, 'IEPomqor2A8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('coney island', 10, 21, 1, 0, 'c_p_TBaHvos');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('ivy', 10, 22, 1, 0, '9nIOx-ezlzA');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('The Man', 11, 23, 1, 0, 'AqAJLh9wuZ0');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Cornelia Street', 11, 24, 1, 0, 'VikHHWrgb4Y');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Enchanted', 12, 25, 1, 0, 'vv3um0BlygY');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Back to December', 12, 26, 1, 0, 'QUwxKWT6m7U');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Mean', 12, 27, 1, 0, 'jYa1eI1hpDE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Sparks Fly', 12, 28, 1, 0, 'oKar-tF__ac');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Last Kiss', 12, 29, 1, 0, '6InmFjIVAv0');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('The Story of Us', 12, 30, 1, 0, 'nN6VR92V70M');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Getaway Car', 13, 31, 1, 0, 'FhPLQVlUiNQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Look What You Made Me Do', 14, 32, 1, 0, '3tmd-ClpJxA');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('The Other Side Of The Door', 15, 33, 1, 0, '425n1NoRtgA');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Picture to Burn', 16, 34, 1, 0, 'yCMqcFAigRg');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('End Game', 17, 35, 1, 0, 'dfnCAmr569k');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('The Joker And The Queen', 18, 36, 2, 0, '2qzcHLyv3N0');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Summertime Sadness', 19, 37, 3, 0, 'TdrL3QxjyVw');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Video Games', 19, 38, 3, 0, 'cE6wxDqdOV0');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Ride', 19, 39, 3, 0, 'Py_-3di1yx0');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Carmen', 19, 40, 3, 0, 'L6K8Uq88BEQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('National Anthem', 19, 41, 3, 0, 'sxDdEPED0h8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Blue Banisters', 20, 42, 3, 0, 'fN0OmdJUl0I');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Arcadia', 20, 43, 3, 0, '4mECX60FVJQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('If You Lie Down With Me', 20, 44, 3, 0, 'xFv0wg_alGk');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Born to Die', 21, 45, 3, 0, 'Bag1gUxuU0g');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Brooklyn Baby', 22, 46, 3, 0, 'T5xcnjAG8pE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('West Coast', 22, 47, 3, 0, 'oKxuiw3iMBE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Cherry', 23, 48, 3, 0, 'uNuMH2i6wdI');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Cola', 24, 49, 3, 0, 'lBakG7KtVZE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Gods & Monsters', 24, 50, 3, 0, 'ORw5Sv0Ch-0');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Mariners Apartment Complex', 25, 51, 3, 0, '1uFv9Ts7Sdw');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Love', 26, 52, 3, 0, '3-NTv0CdFCk');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Dark Paradise', 27, 53, 3, 0, 'l4rhJx2YPo8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Off To The Races', 27, 54, 3, 0, '1CaS4pSpS3c');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('High by the Beach', 28, 55, 3, 0, 'QnxpHIl5Ynw');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Venice Bitch', 29, 56, 3, 0, 'Qg3DxELVPj4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Wildflower Wildfire', 30, 57, 3, 0, 'MQAn157UeKY');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Kryptonite', 31, 58, 4, 0, 'xPU8OAjjS4k');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Loser', 31, 59, 4, 0, '2Ui_Q4qBDJY');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Here Without You', 32, 60, 4, 0, 'kPBzTxZQG5Q');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('In the End', 33, 61, 5, 0, 'eVTXPUF4Oz4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('New Divide', 33, 62, 5, 0, 'ysSxxIqKNN0');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Numb', 34, 63, 5, 0, 'kXYiU_JCYtU');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Faint', 34, 64, 5, 0, 'LYU-8IFcDPw');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Somewhere I Belong', 34, 65, 5, 0, 'zsCD5XCu6CM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('What I''ve Done', 35, 66, 5, 0, '8sgycukafqQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('How You Remind Me', 36, 67, 6, 0, '1cQh1ccqu8M');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Photograph', 37, 68, 6, 0, 'BB0DU4DoPP4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Figured You Out', 38, 69, 6, 0, 'FIjRo-gMlKE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Like a Stone', 39, 70, 7, 0, '7QU1nvuxaMA');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Be Yourself', 40, 71, 7, 0, 'WC5FdFlUcl0');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Bring Me to Life', 41, 72, 8, 0, '3YxaaGgTQYM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Seven Nation Army', 42, 73, 9, 0, '0J2QdDbelmY');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Sugar, We''re Goin Down', 43, 74, 10, 0, 'uhG-vLZrb-g');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Dance, Dance', 44, 75, 10, 0, 'C6MOKXm8x50');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('By the Way', 45, 76, 11, 0, 'JnfyjwChuNU');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Dani California', 46, 77, 11, 0, 'Sb5aq5HcS1A');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('The Pretender', 47, 78, 12, 0, 'SBjQ9tuuTJQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Best of You', 48, 79, 12, 0, 'h_L4Rixya64');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('All My Life', 49, 80, 12, 0, 'xQ04WbgI9rg');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Times Like These', 49, 81, 12, 0, 'rhzmNRtIp8k');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Down With the Sickness', 50, 82, 13, 0, '09LTT0xwdfw');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Inside the Fire', 51, 83, 13, 0, '2Q1SxzEBhnc');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('You''re Gonna Go Far, Kid', 52, 84, 14, 0, 'ql9-82oV2JE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Original Prankster', 53, 85, 14, 0, 'Qp6Qn8IwPf8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('It''s Been Awhile', 54, 86, 15, 0, 'araU0fZj6oQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('So Far Away', 55, 87, 15, 0, 'QCZXjB9DPl4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Drive', 56, 88, 16, 0, 'fgT9zGkiLig');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Boulevard of Broken Dreams', 57, 89, 17, 0, 'Soa3gO7tL-c');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Holiday', 57, 90, 17, 0, 'A1OqtIqzScI');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('American Idiot', 58, 91, 17, 0, 'Ee_uujKuJMI');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Youth of the Nation', 59, 92, 18, 0, 'EDKwCvD56kw');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Second Chance', 60, 93, 19, 0, 'WbsDPbr8qoM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Save Me', 61, 94, 19, 0, 'T8dyxGiBx3g');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Slither', 62, 95, 20, 0, 'BKz2U4fvA4U');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Fall To Pieces', 62, 96, 20, 0, '9JhsUFuqbCM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Fake It', 63, 97, 21, 0, 'gy8HPSIFXEM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Remedy', 64, 98, 21, 0, 'FZLILV18ut8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Pain', 65, 99, 22, 0, 'Ud4HuAzHEUc');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('It''s My Life', 66, 100, 23, 0, 'vx2u5uUu3DE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Coldplay - Viva La Vida', 67, 101, 24, 0, 'dvgZkm1xWPE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Mr. Brightside', 68, 102, 25, 0, 'gGdGFtwCNBE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Welcome to the Black Parade', 69, 103, 26, 0, 'RRKJiM9Njr8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Teenagers', 69, 104, 26, 0, 'k6EQAOmJrbw');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Uprising', 70, 105, 27, 0, 'w8KQmps-Sog');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('My Sacrifice', 71, 106, 28, 0, 'O-fyNgHdmLI');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('With Arms Wide Open', 72, 107, 28, 0, 'gotLhnzWYek');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('I Stand Alone', 73, 108, 29, 0, 'OYjZK_6i37M');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Butterfly', 74, 109, 30, 0, '6FEDrU85FLE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Beautiful Day', 75, 110, 31, 0, 'co6WMzDOh1o');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Are You Gonna Be My Girl', 76, 111, 32, 0, 'tuK6n2Lkza0');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Cold Hard Bitch', 76, 112, 32, 0, '9dRGBjybDSU');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Last Nite', 77, 113, 33, 0, 'TOypSnKFHrE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Home', 78, 114, 34, 0, '7bnX-6sJZBw');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Breath', 79, 115, 35, 0, 'XlqkG4XD2ok');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('The Anthem', 80, 116, 36, 0, 'desJKYvdq9A');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Lifestyles of the Rich & Famous', 80, 117, 36, 0, 'y-jC3H_8Dk4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Through Glass', 81, 118, 37, 0, 'GIzDsGyxsQM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Beverly Hills', 82, 119, 38, 0, 'HL_WvOly7mY');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Hash Pipe', 83, 120, 38, 0, '_9BGLtqqkVI');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Jaded', 84, 121, 39, 0, 'qbexOeoH5hg');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Ocean Avenue', 85, 122, 40, 0, 'X9fLbfzCqWw');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Hanging by a Moment', 86, 123, 41, 0, 'tPnK39ax_AM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('I Don''t Wanna Stop', 87, 124, 42, 0, '2nX6qGeyaGM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Send the Pain Below', 88, 125, 43, 0, 'gpyRI1j9t6c');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Stiff Upper Lip', 89, 126, 44, 0, 'S2Z8WIlaPH4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('I Disappear', 90, 127, 45, 0, 'nYSDC3cHoZs');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('The Day That Never Comes', 91, 128, 45, 0, 'K6AJuRK2NE4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Sweetness', 92, 129, 46, 0, 'ROatPGGMvXg');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Psycho', 93, 130, 47, 0, 'pDdeOncpD5E');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('I''d Do Anything', 94, 131, 48, 0, 'H2M7zo8ZziE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Somewhere Out There', 95, 132, 49, 0, '8SzFaEqbLRM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Steady, as She Goes', 96, 133, 50, 0, 'DXAidGQUuns');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('The Fixer', 97, 134, 51, 0, '036quy0ERkE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Counter Attack-Mankind', 98, 135, 52, 0, 'icSrzREkNJM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Attack on Titan', 98, 136, 52, 0, 'zroFzv7sFis');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('E.M.A', 98, 137, 52, 0, '1hbznMnHymU');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Eye-Water', 98, 138, 52, 0, 'YbJpH9to-9Y');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('attack音D', 99, 139, 53, 0, 'c7NMfDeIMHs');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Barricades', 99, 140, 53, 0, 'BXsjKvdEae4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('So ist es immer', 99, 141, 53, 0, 'vHPnnI3FSLY');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('ERENthe標', 99, 142, 53, 0, 'qLNcTP-JpRw');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('2Volt', 99, 143, 53, 0, 'pSjGAlbcOfg');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('APETITAN', 99, 144, 53, 0, 'eLBnWNLOAZA');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('TheWeightOfLives', 99, 145, 53, 0, 'T6MfY85T2WM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('ymniam-orch', 99, 146, 53, 0, 'gwHvq1whvp0');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('theDOGS', 100, 147, 53, 0, 'iW3NGzslPik');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('the first town ~progressive mix', 101, 148, 54, 0, 'bFu7gH8D50c');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('in the land of twilight, under the moon', 102, 149, 55, 0, 'fgJ-YljvzR0');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('everytime you kissed me', 103, 150, 55, 0, 'IV6s7IKxocU');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Shut Down', 104, 151, 56, 0, 'POe9SOEKotk');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Typa Girl', 104, 152, 56, 0, 'UhxW9Njqqu0');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('The Happiest Girl', 104, 153, 56, 0, 'kVXazE8wR1Q');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Tally', 104, 154, 56, 0, 'VQo4hyWfBQ4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Hard to Love', 104, 155, 56, 0, '7Hr3p1BHC_E');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Yeah Yeah Yeah', 104, 156, 56, 0, 'wQTjv-Xo1gY');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Pink Venom', 105, 157, 56, 0, 'gQlMMD8auMs');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('AS IF IT''S YOUR LAST -KR ver.-', 106, 158, 56, 0, 'Amq-qlqbjYA');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('PLAYING WITH FIRE', 107, 159, 56, 0, '9pdj4iJD08s');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('DDU-DU DDU-DU', 108, 160, 56, 0, 'IHNzOHi8sJs');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Pretty Savage', 109, 161, 56, 0, 'F8c8f2nK82w');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Crazy Over You', 109, 162, 56, 0, 'u7rKGj13pAs');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('You Never Know', 109, 163, 56, 0, '4Kk_iaaHd_Y');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Bet You Wanna', 109, 164, 56, 0, 'gXBdvSj9F2I');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Lovesick Girls', 110, 165, 56, 0, 'dyRsYk0LyA8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Ready For Love', 111, 166, 56, 0, '7WyHtSlvHD4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Kick It', 112, 167, 56, 0, '-h4QsEoPYGg');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Hope Not', 112, 168, 56, 0, 'AqRQvnafWJI');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Forever Young', 113, 169, 56, 0, 'tT5AkN4r3NM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Lovesick Girls', 114, 170, 56, 0, 'kLoqdvCtl9M');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('DDU-DU DDU-DU', 115, 171, 56, 0, 'XiqRE2EH5y4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Minor Feelings', 116, 172, 57, 0, 'sQnzx3rEro8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('This Hell', 116, 173, 57, 0, 'Klk9N84tsAI');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Catch Me In The Air', 116, 174, 57, 0, 'ZW1SlN7YODQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Forgiveness', 116, 175, 57, 0, 'TM6LwKe-JRw');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Your Age', 116, 176, 57, 0, 'cKF4l1l9GJU');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Imagining', 116, 177, 57, 0, 'VpbrFzU6wpM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Frankenstein', 116, 178, 57, 0, 'pLZZW4QPsuc');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Hurricanes', 116, 179, 57, 0, 'uqzKejn5-a8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Send My Love To John', 116, 180, 57, 0, 'hvpPP0L5bsc');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Phantom', 116, 181, 57, 0, 'Q-5melZcPj4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('To Be Alive', 116, 182, 57, 0, '49LCxbzvmBg');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Dynasty', 117, 183, 57, 0, 'AXekXn25GRs');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('STFU!', 117, 184, 57, 0, 'OtgyVGqMrOA');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Akasaka Sad', 117, 185, 57, 0, 'XSl239RQ_mc');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Paradisin''', 117, 186, 57, 0, 'G_v1BVMgJiI');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Love Me 4 Me', 117, 187, 57, 0, 'jGtypOYpUMQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Who''s Gonna Save U Now?', 117, 188, 57, 0, 'sip8XPehfdc');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Tokyo Love Hotel', 117, 189, 57, 0, '7m8wpFC56JM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Chosen Family', 117, 190, 57, 0, '2nlX6qR5HGY');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Snakeskin', 117, 191, 57, 0, 'Dc2KW63YXsg');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Complicated', 118, 192, 58, 0, '5NPBIwQyPWE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Sk8er Boi', 118, 193, 58, 0, 'TIy3n2b7V9k');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('I''m With You', 118, 194, 58, 0, 'dGR65RWwzg8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Losing Grip', 118, 195, 58, 0, 'LOcKckBLouM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Mobile', 118, 196, 58, 0, 'KuuhcltChKc');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Girlfriend', 119, 197, 58, 0, 'Bg59q4puhmg');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('What The Hell', 120, 198, 58, 0, 'tQmEd_UeeIk');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Smile', 120, 199, 58, 0, 'KagvExF-ijc');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Wish You Were Here', 120, 200, 58, 0, 'VT1-sitWRtY');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Love It When You Hate Me', 121, 201, 58, 0, 'lPi1jj12WC8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('When You''re Gone', 122, 202, 58, 0, '0G3_kG5FFfQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Innocence', 122, 203, 58, 0, 'hFlJZKrG2Uw');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Here''s to Never Growing Up', 123, 204, 58, 0, 'sXd2WxoOP5g');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Let Me Go', 123, 205, 58, 0, 'AqajUg85Ax4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Rock N Roll', 123, 206, 58, 0, 'uuNTO31FlY8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Hello Kitty', 123, 207, 58, 0, 'LiaYDPRedWQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Bite Me', 124, 208, 58, 0, 'ciqUEV9F0OY');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('My Happy Ending', 125, 209, 58, 0, 's8QYxmpuyxg');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Don''t Tell Me', 125, 210, 58, 0, 'zMbIipvQL0c');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Nobody''s Home', 125, 211, 58, 0, 'NGFSNE18Ywc');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('He Wasn''t', 125, 212, 58, 0, 'onPaBhiJxEE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('I Always Get What I Want', 125, 213, 58, 0, 'nO4q2WuurZk');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Fall To Pieces', 125, 214, 58, 0, 'EfcuPzCDzas');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('We Are Warriors', 126, 215, 58, 0, '3tBk7ONm95Q');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Hot', 127, 216, 58, 0, 'fzb75m8NuMQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Bois Lie', 128, 217, 58, 0, 'P82ihMcsjKw');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Alice', 129, 218, 58, 0, 'YI4m-l2yRZA');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Keep Holding On', 130, 219, 58, 0, 'trp6FZs2zlM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Breakaway', 131, 220, 58, 0, 'oc7JLUvY9xI');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Fly', 132, 221, 58, 0, '7dcNG6-5O2o');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('I Don''t Give', 133, 222, 58, 0, 'Yxf8ODiJDrY');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Give You What You Like', 134, 223, 58, 0, 'gUqL6meIfdA');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Bad Girl', 134, 224, 58, 0, 'TMIkAY_Xafk');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Bored', 135, 225, 59, 0, 'cnGW8NR-toE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('TV', 136, 226, 59, 0, '_JGGLJMpVks');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('NDA', 137, 227, 59, 0, 'OORBa32WFcM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Male Fantasy', 138, 228, 59, 0, 'G_BhUxx-cwk');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Billie Bossa Nova', 139, 229, 59, 0, '4tZ969oc-yI');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('GOLDWING', 139, 230, 59, 0, 'JpL7scu-EmY');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('idontwannabeyouanymore', 140, 231, 59, 0, '-tn2S3kJlyU');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('COPYCAT', 141, 232, 59, 0, 'ebb5AinKxWI');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('watch', 141, 233, 59, 0, '9dobJDxPEzM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('bitches broken hearts', 142, 234, 59, 0, 'qpQSjf-0Lc8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Six Feet Under', 143, 235, 59, 0, 'FQ0iq10ULNA');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('8', 144, 236, 59, 0, 'OZYd9JxithE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('goodbye', 144, 237, 59, 0, 'vciZvVJyNYU');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Shinigami Eyes', 145, 238, 60, 0, 'pzPElFdxMCM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('abcdefu', 146, 239, 61, 0, 'NaFd8ucHLuo');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Valentine', 147, 240, 62, 0, 'ZxarOZ0JBcc');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Down', 148, 241, 63, 0, 'VQ9iAlm-sJ8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('The Nowhere Inn', 149, 242, 63, 0, 'z1O91hhKwYE');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Los Ageless', 150, 243, 63, 0, 'G8jxAKmojxY');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Growing Up', 151, 244, 64, 0, 'Wm1Sew7lAG4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Clementine', 152, 245, 65, 0, 'ygbwVO1N_Eo');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Aubade', 153, 246, 66, 0, 'hSZGZx9VBzQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Chaise Longue', 154, 247, 67, 0, 'Zd9jeJk2UHQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Green Light', 155, 248, 68, 0, 'dMK_npDG12Q');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Still Into You', 156, 249, 69, 0, 'OblL026SvD4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('prom dress', 157, 250, 70, 0, 'AeUeLzBO0go');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Sofia', 158, 251, 71, 0, 'wD__jpWgWkQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Bags', 159, 252, 71, 0, 'L9HYJbe9Y18');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('1950', 160, 253, 72, 0, 'LNxWTS25Tbk');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Blood In The Cut', 161, 254, 73, 0, 'k2WcOdz96ko');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Giver', 161, 255, 73, 0, 'nt26yjdItdA');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('I Said Hi', 162, 256, 74, 0, '1K4KwuV2l4s');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Mess Her Up', 162, 257, 74, 0, 'hCjcgoubkPM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('When I''m Small', 163, 258, 75, 0, '28tZ-S1LFok');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('In a Spiral', 164, 259, 75, 0, 'WzGSI8XYPHs');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Dream', 165, 260, 76, 0, 'bqsiJPK-94Q');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Now I''m In It', 166, 261, 77, 0, 'G-UnzRM24IM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Simmer', 167, 262, 78, 0, '8lSj5k2K7w0');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Seventeen', 168, 263, 79, 0, 'j7sTHoeH0eA');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Miracle', 169, 264, 80, 0, 'e1YqueG2gtQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Hallucinations', 170, 265, 81, 0, 'NzdUeJnn0gM');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Monday', 171, 266, 82, 0, '654WbtSEm_8');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Learn to Live', 172, 267, 83, 0, 'I51C1GtzRs4');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Smile', 173, 268, 84, 0, 'NV39h7GHDYs');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Pretty Lady', 174, 269, 85, 0, 'mj2_4T_qLLQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Blackbird', 175, 270, 85, 0, 'zYZeF26fO68');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('please put me in a medically induced coma', 176, 271, 86, 0, 'PzUkYUWjDyA');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Fall to Pieces', 177, 272, 87, 0, 'j0tD-2C9vsw');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('SUPERBLOOM', 178, 273, 88, 0, 'tv3gjE3zIIs');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Good Thing Gone', 179, 274, 89, 0, 'f9bSMmgi4i0');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Rockstar', 180, 275, 90, 0, '2l7-f-NZUDk');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Questions', 181, 276, 91, 0, 'VchylRsWmcQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Crying', 182, 277, 92, 0, 'pN-O-z4wpVI');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Funeral', 183, 278, 93, 0, 'X-z4-q3Xeqg');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Lovin Is Bible', 184, 279, 94, 0, 'qsy6TE8lrLQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Heaven', 185, 280, 95, 0, 'qbmYNpVSbUk');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('One Day We''ll Make It Big', 186, 281, 96, 0, 'gd5FZZnwKoQ');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Intentions', 187, 282, 97, 0, 'bDA040TQ5Fk');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('Divorce Song', 188, 283, 98, 0, 'RhGP2vTn5Tw');
insert into public.songs (Song_Name, Album_ID, Song_ID, Artist_ID, Listens, Song_URL) values ('This Love', 1, 3, 1, 69, 'mvxQYPR4lmU');
