UPDATE public.songs SET "Song_Name" = 'Shake It Off', "Album_ID" = 1, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'nfWlot6h_JM' WHERE "Song_ID" = 1;
UPDATE public.songs SET "Song_Name" = 'Wildest Dreams', "Album_ID" = 1, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'CUr_UwUUXzU' WHERE "Song_ID" = 2;
UPDATE public.songs SET "Song_Name" = 'Blank Space', "Album_ID" = 1, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'e-ORhEE9VVg' WHERE "Song_ID" = 4;
UPDATE public.songs SET "Song_Name" = 'Style', "Album_ID" = 1, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = '-CmadmM5cOk' WHERE "Song_ID" = 5;
UPDATE public.songs SET "Song_Name" = 'Bad Blood', "Album_ID" = 1, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'QcIy9NiNbmo' WHERE "Song_ID" = 6;
UPDATE public.songs SET "Song_Name" = 'All Too Well: The Short Film', "Album_ID" = 2, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'tollGa3S0o8' WHERE "Song_ID" = 7;
UPDATE public.songs SET "Song_Name" = 'You Belong With Me', "Album_ID" = 3, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'vwp8Ur6tO-8' WHERE "Song_ID" = 8;
UPDATE public.songs SET "Song_Name" = 'Love Story', "Album_ID" = 3, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'aXzVF3XeS8M' WHERE "Song_ID" = 9;
UPDATE public.songs SET "Song_Name" = 'Fifteen', "Album_ID" = 3, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'rLCol1C3ouc' WHERE "Song_ID" = 10;
UPDATE public.songs SET "Song_Name" = '22', "Album_ID" = 4, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = '9boiT64sm0Q' WHERE "Song_ID" = 11;
UPDATE public.songs SET "Song_Name" = 'Red', "Album_ID" = 4, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'R_rUYuFtNO4' WHERE "Song_ID" = 12;
UPDATE public.songs SET "Song_Name" = 'All Too Well', "Album_ID" = 4, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'F8Jxo15Vfic' WHERE "Song_ID" = 13;
UPDATE public.songs SET "Song_Name" = 'I Knew You Were Trouble', "Album_ID" = 5, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'TqAollrUJdA' WHERE "Song_ID" = 14;
UPDATE public.songs SET "Song_Name" = 'Everything Has Changed', "Album_ID" = 5, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'w1oM3kQpXRo' WHERE "Song_ID" = 15;
UPDATE public.songs SET "Song_Name" = 'right where you left me', "Album_ID" = 6, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'Ur_wAcYDnuA' WHERE "Song_ID" = 16;
UPDATE public.songs SET "Song_Name" = 'Cruel Summer', "Album_ID" = 7, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'ic8j13piAhQ' WHERE "Song_ID" = 17;
UPDATE public.songs SET "Song_Name" = 'gold rush', "Album_ID" = 8, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'Pz-f9mM3Ms8' WHERE "Song_ID" = 18;
UPDATE public.songs SET "Song_Name" = 'Run', "Album_ID" = 9, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'flv8AEWrRMI' WHERE "Song_ID" = 19;
UPDATE public.songs SET "Song_Name" = 'no body, no crime', "Album_ID" = 10, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'IEPomqor2A8' WHERE "Song_ID" = 20;
UPDATE public.songs SET "Song_Name" = 'coney island', "Album_ID" = 10, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'c_p_TBaHvos' WHERE "Song_ID" = 21;
UPDATE public.songs SET "Song_Name" = 'ivy', "Album_ID" = 10, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = '9nIOx-ezlzA' WHERE "Song_ID" = 22;
UPDATE public.songs SET "Song_Name" = 'The Man', "Album_ID" = 11, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'AqAJLh9wuZ0' WHERE "Song_ID" = 23;
UPDATE public.songs SET "Song_Name" = 'Cornelia Street', "Album_ID" = 11, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'VikHHWrgb4Y' WHERE "Song_ID" = 24;
UPDATE public.songs SET "Song_Name" = 'Enchanted', "Album_ID" = 12, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'vv3um0BlygY' WHERE "Song_ID" = 25;
UPDATE public.songs SET "Song_Name" = 'Back to December', "Album_ID" = 12, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'QUwxKWT6m7U' WHERE "Song_ID" = 26;
UPDATE public.songs SET "Song_Name" = 'Mean', "Album_ID" = 12, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'jYa1eI1hpDE' WHERE "Song_ID" = 27;
UPDATE public.songs SET "Song_Name" = 'Sparks Fly', "Album_ID" = 12, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'oKar-tF__ac' WHERE "Song_ID" = 28;
UPDATE public.songs SET "Song_Name" = 'Last Kiss', "Album_ID" = 12, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = '6InmFjIVAv0' WHERE "Song_ID" = 29;
UPDATE public.songs SET "Song_Name" = 'The Story of Us', "Album_ID" = 12, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'nN6VR92V70M' WHERE "Song_ID" = 30;
UPDATE public.songs SET "Song_Name" = 'Getaway Car', "Album_ID" = 13, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'FhPLQVlUiNQ' WHERE "Song_ID" = 31;
UPDATE public.songs SET "Song_Name" = 'Look What You Made Me Do', "Album_ID" = 14, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = '3tmd-ClpJxA' WHERE "Song_ID" = 32;
UPDATE public.songs SET "Song_Name" = 'The Other Side Of The Door', "Album_ID" = 15, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = '425n1NoRtgA' WHERE "Song_ID" = 33;
UPDATE public.songs SET "Song_Name" = 'Picture to Burn', "Album_ID" = 16, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'yCMqcFAigRg' WHERE "Song_ID" = 34;
UPDATE public.songs SET "Song_Name" = 'End Game', "Album_ID" = 17, "Artist_ID" = 1, "Listens" = 0, "Song_URL" = 'dfnCAmr569k' WHERE "Song_ID" = 35;
UPDATE public.songs SET "Song_Name" = 'The Joker And The Queen', "Album_ID" = 18, "Artist_ID" = 2, "Listens" = 0, "Song_URL" = '2qzcHLyv3N0' WHERE "Song_ID" = 36;
UPDATE public.songs SET "Song_Name" = 'Summertime Sadness', "Album_ID" = 19, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'TdrL3QxjyVw' WHERE "Song_ID" = 37;
UPDATE public.songs SET "Song_Name" = 'Video Games', "Album_ID" = 19, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'cE6wxDqdOV0' WHERE "Song_ID" = 38;
UPDATE public.songs SET "Song_Name" = 'Ride', "Album_ID" = 19, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'Py_-3di1yx0' WHERE "Song_ID" = 39;
UPDATE public.songs SET "Song_Name" = 'Carmen', "Album_ID" = 19, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'L6K8Uq88BEQ' WHERE "Song_ID" = 40;
UPDATE public.songs SET "Song_Name" = 'National Anthem', "Album_ID" = 19, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'sxDdEPED0h8' WHERE "Song_ID" = 41;
UPDATE public.songs SET "Song_Name" = 'Blue Banisters', "Album_ID" = 20, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'fN0OmdJUl0I' WHERE "Song_ID" = 42;
UPDATE public.songs SET "Song_Name" = 'Arcadia', "Album_ID" = 20, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = '4mECX60FVJQ' WHERE "Song_ID" = 43;
UPDATE public.songs SET "Song_Name" = 'If You Lie Down With Me', "Album_ID" = 20, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'xFv0wg_alGk' WHERE "Song_ID" = 44;
UPDATE public.songs SET "Song_Name" = 'Born to Die', "Album_ID" = 21, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'Bag1gUxuU0g' WHERE "Song_ID" = 45;
UPDATE public.songs SET "Song_Name" = 'Brooklyn Baby', "Album_ID" = 22, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'T5xcnjAG8pE' WHERE "Song_ID" = 46;
UPDATE public.songs SET "Song_Name" = 'West Coast', "Album_ID" = 22, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'oKxuiw3iMBE' WHERE "Song_ID" = 47;
UPDATE public.songs SET "Song_Name" = 'Cherry', "Album_ID" = 23, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'uNuMH2i6wdI' WHERE "Song_ID" = 48;
UPDATE public.songs SET "Song_Name" = 'Cola', "Album_ID" = 24, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'lBakG7KtVZE' WHERE "Song_ID" = 49;
UPDATE public.songs SET "Song_Name" = 'Gods & Monsters', "Album_ID" = 24, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'ORw5Sv0Ch-0' WHERE "Song_ID" = 50;
UPDATE public.songs SET "Song_Name" = 'Mariners Apartment Complex', "Album_ID" = 25, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = '1uFv9Ts7Sdw' WHERE "Song_ID" = 51;
UPDATE public.songs SET "Song_Name" = 'Love', "Album_ID" = 26, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = '3-NTv0CdFCk' WHERE "Song_ID" = 52;
UPDATE public.songs SET "Song_Name" = 'Dark Paradise', "Album_ID" = 27, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'l4rhJx2YPo8' WHERE "Song_ID" = 53;
UPDATE public.songs SET "Song_Name" = 'Off To The Races', "Album_ID" = 27, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = '1CaS4pSpS3c' WHERE "Song_ID" = 54;
UPDATE public.songs SET "Song_Name" = 'High by the Beach', "Album_ID" = 28, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'QnxpHIl5Ynw' WHERE "Song_ID" = 55;
UPDATE public.songs SET "Song_Name" = 'Venice Bitch', "Album_ID" = 29, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'Qg3DxELVPj4' WHERE "Song_ID" = 56;
UPDATE public.songs SET "Song_Name" = 'Wildflower Wildfire', "Album_ID" = 30, "Artist_ID" = 3, "Listens" = 0, "Song_URL" = 'MQAn157UeKY' WHERE "Song_ID" = 57;
UPDATE public.songs SET "Song_Name" = 'Kryptonite', "Album_ID" = 31, "Artist_ID" = 4, "Listens" = 0, "Song_URL" = 'xPU8OAjjS4k' WHERE "Song_ID" = 58;
UPDATE public.songs SET "Song_Name" = 'Loser', "Album_ID" = 31, "Artist_ID" = 4, "Listens" = 0, "Song_URL" = '2Ui_Q4qBDJY' WHERE "Song_ID" = 59;
UPDATE public.songs SET "Song_Name" = 'Here Without You', "Album_ID" = 32, "Artist_ID" = 4, "Listens" = 0, "Song_URL" = 'kPBzTxZQG5Q' WHERE "Song_ID" = 60;
UPDATE public.songs SET "Song_Name" = 'In the End', "Album_ID" = 33, "Artist_ID" = 5, "Listens" = 0, "Song_URL" = 'eVTXPUF4Oz4' WHERE "Song_ID" = 61;
UPDATE public.songs SET "Song_Name" = 'New Divide', "Album_ID" = 33, "Artist_ID" = 5, "Listens" = 0, "Song_URL" = 'ysSxxIqKNN0' WHERE "Song_ID" = 62;
UPDATE public.songs SET "Song_Name" = 'Numb', "Album_ID" = 34, "Artist_ID" = 5, "Listens" = 0, "Song_URL" = 'kXYiU_JCYtU' WHERE "Song_ID" = 63;
UPDATE public.songs SET "Song_Name" = 'Faint', "Album_ID" = 34, "Artist_ID" = 5, "Listens" = 0, "Song_URL" = 'LYU-8IFcDPw' WHERE "Song_ID" = 64;
UPDATE public.songs SET "Song_Name" = 'Somewhere I Belong', "Album_ID" = 34, "Artist_ID" = 5, "Listens" = 0, "Song_URL" = 'zsCD5XCu6CM' WHERE "Song_ID" = 65;
UPDATE public.songs SET "Song_Name" = 'What I''ve Done', "Album_ID" = 35, "Artist_ID" = 5, "Listens" = 0, "Song_URL" = '8sgycukafqQ' WHERE "Song_ID" = 66;
UPDATE public.songs SET "Song_Name" = 'How You Remind Me', "Album_ID" = 36, "Artist_ID" = 6, "Listens" = 0, "Song_URL" = '1cQh1ccqu8M' WHERE "Song_ID" = 67;
UPDATE public.songs SET "Song_Name" = 'Photograph', "Album_ID" = 37, "Artist_ID" = 6, "Listens" = 0, "Song_URL" = 'BB0DU4DoPP4' WHERE "Song_ID" = 68;
UPDATE public.songs SET "Song_Name" = 'Figured You Out', "Album_ID" = 38, "Artist_ID" = 6, "Listens" = 0, "Song_URL" = 'FIjRo-gMlKE' WHERE "Song_ID" = 69;
UPDATE public.songs SET "Song_Name" = 'Like a Stone', "Album_ID" = 39, "Artist_ID" = 7, "Listens" = 0, "Song_URL" = '7QU1nvuxaMA' WHERE "Song_ID" = 70;
UPDATE public.songs SET "Song_Name" = 'Be Yourself', "Album_ID" = 40, "Artist_ID" = 7, "Listens" = 0, "Song_URL" = 'WC5FdFlUcl0' WHERE "Song_ID" = 71;
UPDATE public.songs SET "Song_Name" = 'Bring Me to Life', "Album_ID" = 41, "Artist_ID" = 8, "Listens" = 0, "Song_URL" = '3YxaaGgTQYM' WHERE "Song_ID" = 72;
UPDATE public.songs SET "Song_Name" = 'Seven Nation Army', "Album_ID" = 42, "Artist_ID" = 9, "Listens" = 0, "Song_URL" = '0J2QdDbelmY' WHERE "Song_ID" = 73;
UPDATE public.songs SET "Song_Name" = 'Sugar, We''re Goin Down', "Album_ID" = 43, "Artist_ID" = 10, "Listens" = 0, "Song_URL" = 'uhG-vLZrb-g' WHERE "Song_ID" = 74;
UPDATE public.songs SET "Song_Name" = 'Dance, Dance', "Album_ID" = 44, "Artist_ID" = 10, "Listens" = 0, "Song_URL" = 'C6MOKXm8x50' WHERE "Song_ID" = 75;
UPDATE public.songs SET "Song_Name" = 'By the Way', "Album_ID" = 45, "Artist_ID" = 11, "Listens" = 0, "Song_URL" = 'JnfyjwChuNU' WHERE "Song_ID" = 76;
UPDATE public.songs SET "Song_Name" = 'Dani California', "Album_ID" = 46, "Artist_ID" = 11, "Listens" = 0, "Song_URL" = 'Sb5aq5HcS1A' WHERE "Song_ID" = 77;
UPDATE public.songs SET "Song_Name" = 'The Pretender', "Album_ID" = 47, "Artist_ID" = 12, "Listens" = 0, "Song_URL" = 'SBjQ9tuuTJQ' WHERE "Song_ID" = 78;
UPDATE public.songs SET "Song_Name" = 'Best of You', "Album_ID" = 48, "Artist_ID" = 12, "Listens" = 0, "Song_URL" = 'h_L4Rixya64' WHERE "Song_ID" = 79;
UPDATE public.songs SET "Song_Name" = 'All My Life', "Album_ID" = 49, "Artist_ID" = 12, "Listens" = 0, "Song_URL" = 'xQ04WbgI9rg' WHERE "Song_ID" = 80;
UPDATE public.songs SET "Song_Name" = 'Times Like These', "Album_ID" = 49, "Artist_ID" = 12, "Listens" = 0, "Song_URL" = 'rhzmNRtIp8k' WHERE "Song_ID" = 81;
UPDATE public.songs SET "Song_Name" = 'Down With the Sickness', "Album_ID" = 50, "Artist_ID" = 13, "Listens" = 0, "Song_URL" = '09LTT0xwdfw' WHERE "Song_ID" = 82;
UPDATE public.songs SET "Song_Name" = 'Inside the Fire', "Album_ID" = 51, "Artist_ID" = 13, "Listens" = 0, "Song_URL" = '2Q1SxzEBhnc' WHERE "Song_ID" = 83;
UPDATE public.songs SET "Song_Name" = 'You''re Gonna Go Far, Kid', "Album_ID" = 52, "Artist_ID" = 14, "Listens" = 0, "Song_URL" = 'ql9-82oV2JE' WHERE "Song_ID" = 84;
UPDATE public.songs SET "Song_Name" = 'Original Prankster', "Album_ID" = 53, "Artist_ID" = 14, "Listens" = 0, "Song_URL" = 'Qp6Qn8IwPf8' WHERE "Song_ID" = 85;
UPDATE public.songs SET "Song_Name" = 'It''s Been Awhile', "Album_ID" = 54, "Artist_ID" = 15, "Listens" = 0, "Song_URL" = 'araU0fZj6oQ' WHERE "Song_ID" = 86;
UPDATE public.songs SET "Song_Name" = 'So Far Away', "Album_ID" = 55, "Artist_ID" = 15, "Listens" = 0, "Song_URL" = 'QCZXjB9DPl4' WHERE "Song_ID" = 87;
UPDATE public.songs SET "Song_Name" = 'Drive', "Album_ID" = 56, "Artist_ID" = 16, "Listens" = 0, "Song_URL" = 'fgT9zGkiLig' WHERE "Song_ID" = 88;
UPDATE public.songs SET "Song_Name" = 'Boulevard of Broken Dreams', "Album_ID" = 57, "Artist_ID" = 17, "Listens" = 0, "Song_URL" = 'Soa3gO7tL-c' WHERE "Song_ID" = 89;
UPDATE public.songs SET "Song_Name" = 'Holiday', "Album_ID" = 57, "Artist_ID" = 17, "Listens" = 0, "Song_URL" = 'A1OqtIqzScI' WHERE "Song_ID" = 90;
UPDATE public.songs SET "Song_Name" = 'American Idiot', "Album_ID" = 58, "Artist_ID" = 17, "Listens" = 0, "Song_URL" = 'Ee_uujKuJMI' WHERE "Song_ID" = 91;
UPDATE public.songs SET "Song_Name" = 'Youth of the Nation', "Album_ID" = 59, "Artist_ID" = 18, "Listens" = 0, "Song_URL" = 'EDKwCvD56kw' WHERE "Song_ID" = 92;
UPDATE public.songs SET "Song_Name" = 'Second Chance', "Album_ID" = 60, "Artist_ID" = 19, "Listens" = 0, "Song_URL" = 'WbsDPbr8qoM' WHERE "Song_ID" = 93;
UPDATE public.songs SET "Song_Name" = 'Save Me', "Album_ID" = 61, "Artist_ID" = 19, "Listens" = 0, "Song_URL" = 'T8dyxGiBx3g' WHERE "Song_ID" = 94;
UPDATE public.songs SET "Song_Name" = 'Slither', "Album_ID" = 62, "Artist_ID" = 20, "Listens" = 0, "Song_URL" = 'BKz2U4fvA4U' WHERE "Song_ID" = 95;
UPDATE public.songs SET "Song_Name" = 'Fall To Pieces', "Album_ID" = 62, "Artist_ID" = 20, "Listens" = 0, "Song_URL" = '9JhsUFuqbCM' WHERE "Song_ID" = 96;
UPDATE public.songs SET "Song_Name" = 'Fake It', "Album_ID" = 63, "Artist_ID" = 21, "Listens" = 0, "Song_URL" = 'gy8HPSIFXEM' WHERE "Song_ID" = 97;
UPDATE public.songs SET "Song_Name" = 'Remedy', "Album_ID" = 64, "Artist_ID" = 21, "Listens" = 0, "Song_URL" = 'FZLILV18ut8' WHERE "Song_ID" = 98;
UPDATE public.songs SET "Song_Name" = 'Pain', "Album_ID" = 65, "Artist_ID" = 22, "Listens" = 0, "Song_URL" = 'Ud4HuAzHEUc' WHERE "Song_ID" = 99;
UPDATE public.songs SET "Song_Name" = 'It''s My Life', "Album_ID" = 66, "Artist_ID" = 23, "Listens" = 0, "Song_URL" = 'vx2u5uUu3DE' WHERE "Song_ID" = 100;
UPDATE public.songs SET "Song_Name" = 'Coldplay - Viva La Vida', "Album_ID" = 67, "Artist_ID" = 24, "Listens" = 0, "Song_URL" = 'dvgZkm1xWPE' WHERE "Song_ID" = 101;
UPDATE public.songs SET "Song_Name" = 'Mr. Brightside', "Album_ID" = 68, "Artist_ID" = 25, "Listens" = 0, "Song_URL" = 'gGdGFtwCNBE' WHERE "Song_ID" = 102;
UPDATE public.songs SET "Song_Name" = 'Welcome to the Black Parade', "Album_ID" = 69, "Artist_ID" = 26, "Listens" = 0, "Song_URL" = 'RRKJiM9Njr8' WHERE "Song_ID" = 103;
UPDATE public.songs SET "Song_Name" = 'Teenagers', "Album_ID" = 69, "Artist_ID" = 26, "Listens" = 0, "Song_URL" = 'k6EQAOmJrbw' WHERE "Song_ID" = 104;
UPDATE public.songs SET "Song_Name" = 'Uprising', "Album_ID" = 70, "Artist_ID" = 27, "Listens" = 0, "Song_URL" = 'w8KQmps-Sog' WHERE "Song_ID" = 105;
UPDATE public.songs SET "Song_Name" = 'My Sacrifice', "Album_ID" = 71, "Artist_ID" = 28, "Listens" = 0, "Song_URL" = 'O-fyNgHdmLI' WHERE "Song_ID" = 106;
UPDATE public.songs SET "Song_Name" = 'With Arms Wide Open', "Album_ID" = 72, "Artist_ID" = 28, "Listens" = 0, "Song_URL" = 'gotLhnzWYek' WHERE "Song_ID" = 107;
UPDATE public.songs SET "Song_Name" = 'I Stand Alone', "Album_ID" = 73, "Artist_ID" = 29, "Listens" = 0, "Song_URL" = 'OYjZK_6i37M' WHERE "Song_ID" = 108;
UPDATE public.songs SET "Song_Name" = 'Butterfly', "Album_ID" = 74, "Artist_ID" = 30, "Listens" = 0, "Song_URL" = '6FEDrU85FLE' WHERE "Song_ID" = 109;
UPDATE public.songs SET "Song_Name" = 'Beautiful Day', "Album_ID" = 75, "Artist_ID" = 31, "Listens" = 0, "Song_URL" = 'co6WMzDOh1o' WHERE "Song_ID" = 110;
UPDATE public.songs SET "Song_Name" = 'Are You Gonna Be My Girl', "Album_ID" = 76, "Artist_ID" = 32, "Listens" = 0, "Song_URL" = 'tuK6n2Lkza0' WHERE "Song_ID" = 111;
UPDATE public.songs SET "Song_Name" = 'Cold Hard Bitch', "Album_ID" = 76, "Artist_ID" = 32, "Listens" = 0, "Song_URL" = '9dRGBjybDSU' WHERE "Song_ID" = 112;
UPDATE public.songs SET "Song_Name" = 'Last Nite', "Album_ID" = 77, "Artist_ID" = 33, "Listens" = 0, "Song_URL" = 'TOypSnKFHrE' WHERE "Song_ID" = 113;
UPDATE public.songs SET "Song_Name" = 'Home', "Album_ID" = 78, "Artist_ID" = 34, "Listens" = 0, "Song_URL" = '7bnX-6sJZBw' WHERE "Song_ID" = 114;
UPDATE public.songs SET "Song_Name" = 'Breath', "Album_ID" = 79, "Artist_ID" = 35, "Listens" = 0, "Song_URL" = 'XlqkG4XD2ok' WHERE "Song_ID" = 115;
UPDATE public.songs SET "Song_Name" = 'The Anthem', "Album_ID" = 80, "Artist_ID" = 36, "Listens" = 0, "Song_URL" = 'desJKYvdq9A' WHERE "Song_ID" = 116;
UPDATE public.songs SET "Song_Name" = 'Lifestyles of the Rich & Famous', "Album_ID" = 80, "Artist_ID" = 36, "Listens" = 0, "Song_URL" = 'y-jC3H_8Dk4' WHERE "Song_ID" = 117;
UPDATE public.songs SET "Song_Name" = 'Through Glass', "Album_ID" = 81, "Artist_ID" = 37, "Listens" = 0, "Song_URL" = 'GIzDsGyxsQM' WHERE "Song_ID" = 118;
UPDATE public.songs SET "Song_Name" = 'Beverly Hills', "Album_ID" = 82, "Artist_ID" = 38, "Listens" = 0, "Song_URL" = 'HL_WvOly7mY' WHERE "Song_ID" = 119;
UPDATE public.songs SET "Song_Name" = 'Hash Pipe', "Album_ID" = 83, "Artist_ID" = 38, "Listens" = 0, "Song_URL" = '_9BGLtqqkVI' WHERE "Song_ID" = 120;
UPDATE public.songs SET "Song_Name" = 'Jaded', "Album_ID" = 84, "Artist_ID" = 39, "Listens" = 0, "Song_URL" = 'qbexOeoH5hg' WHERE "Song_ID" = 121;
UPDATE public.songs SET "Song_Name" = 'Ocean Avenue', "Album_ID" = 85, "Artist_ID" = 40, "Listens" = 0, "Song_URL" = 'X9fLbfzCqWw' WHERE "Song_ID" = 122;
UPDATE public.songs SET "Song_Name" = 'Hanging by a Moment', "Album_ID" = 86, "Artist_ID" = 41, "Listens" = 0, "Song_URL" = 'tPnK39ax_AM' WHERE "Song_ID" = 123;
UPDATE public.songs SET "Song_Name" = 'I Don''t Wanna Stop', "Album_ID" = 87, "Artist_ID" = 42, "Listens" = 0, "Song_URL" = '2nX6qGeyaGM' WHERE "Song_ID" = 124;
UPDATE public.songs SET "Song_Name" = 'Send the Pain Below', "Album_ID" = 88, "Artist_ID" = 43, "Listens" = 0, "Song_URL" = 'gpyRI1j9t6c' WHERE "Song_ID" = 125;
UPDATE public.songs SET "Song_Name" = 'Stiff Upper Lip', "Album_ID" = 89, "Artist_ID" = 44, "Listens" = 0, "Song_URL" = 'S2Z8WIlaPH4' WHERE "Song_ID" = 126;
UPDATE public.songs SET "Song_Name" = 'I Disappear', "Album_ID" = 90, "Artist_ID" = 45, "Listens" = 0, "Song_URL" = 'nYSDC3cHoZs' WHERE "Song_ID" = 127;
UPDATE public.songs SET "Song_Name" = 'The Day That Never Comes', "Album_ID" = 91, "Artist_ID" = 45, "Listens" = 0, "Song_URL" = 'K6AJuRK2NE4' WHERE "Song_ID" = 128;
UPDATE public.songs SET "Song_Name" = 'Sweetness', "Album_ID" = 92, "Artist_ID" = 46, "Listens" = 0, "Song_URL" = 'ROatPGGMvXg' WHERE "Song_ID" = 129;
UPDATE public.songs SET "Song_Name" = 'Psycho', "Album_ID" = 93, "Artist_ID" = 47, "Listens" = 0, "Song_URL" = 'pDdeOncpD5E' WHERE "Song_ID" = 130;
UPDATE public.songs SET "Song_Name" = 'I''d Do Anything', "Album_ID" = 94, "Artist_ID" = 48, "Listens" = 0, "Song_URL" = 'H2M7zo8ZziE' WHERE "Song_ID" = 131;
UPDATE public.songs SET "Song_Name" = 'Somewhere Out There', "Album_ID" = 95, "Artist_ID" = 49, "Listens" = 0, "Song_URL" = '8SzFaEqbLRM' WHERE "Song_ID" = 132;
UPDATE public.songs SET "Song_Name" = 'Steady, as She Goes', "Album_ID" = 96, "Artist_ID" = 50, "Listens" = 0, "Song_URL" = 'DXAidGQUuns' WHERE "Song_ID" = 133;
UPDATE public.songs SET "Song_Name" = 'The Fixer', "Album_ID" = 97, "Artist_ID" = 51, "Listens" = 0, "Song_URL" = '036quy0ERkE' WHERE "Song_ID" = 134;
UPDATE public.songs SET "Song_Name" = 'Counter Attack-Mankind', "Album_ID" = 98, "Artist_ID" = 52, "Listens" = 0, "Song_URL" = 'icSrzREkNJM' WHERE "Song_ID" = 135;
UPDATE public.songs SET "Song_Name" = 'Attack on Titan', "Album_ID" = 98, "Artist_ID" = 52, "Listens" = 0, "Song_URL" = 'zroFzv7sFis' WHERE "Song_ID" = 136;
UPDATE public.songs SET "Song_Name" = 'E.M.A', "Album_ID" = 98, "Artist_ID" = 52, "Listens" = 0, "Song_URL" = '1hbznMnHymU' WHERE "Song_ID" = 137;
UPDATE public.songs SET "Song_Name" = 'Eye-Water', "Album_ID" = 98, "Artist_ID" = 52, "Listens" = 0, "Song_URL" = 'YbJpH9to-9Y' WHERE "Song_ID" = 138;
UPDATE public.songs SET "Song_Name" = 'attack音D', "Album_ID" = 99, "Artist_ID" = 53, "Listens" = 0, "Song_URL" = 'c7NMfDeIMHs' WHERE "Song_ID" = 139;
UPDATE public.songs SET "Song_Name" = 'Barricades', "Album_ID" = 99, "Artist_ID" = 53, "Listens" = 0, "Song_URL" = 'BXsjKvdEae4' WHERE "Song_ID" = 140;
UPDATE public.songs SET "Song_Name" = 'So ist es immer', "Album_ID" = 99, "Artist_ID" = 53, "Listens" = 0, "Song_URL" = 'vHPnnI3FSLY' WHERE "Song_ID" = 141;
UPDATE public.songs SET "Song_Name" = 'ERENthe標', "Album_ID" = 99, "Artist_ID" = 53, "Listens" = 0, "Song_URL" = 'qLNcTP-JpRw' WHERE "Song_ID" = 142;
UPDATE public.songs SET "Song_Name" = '2Volt', "Album_ID" = 99, "Artist_ID" = 53, "Listens" = 0, "Song_URL" = 'pSjGAlbcOfg' WHERE "Song_ID" = 143;
UPDATE public.songs SET "Song_Name" = 'APETITAN', "Album_ID" = 99, "Artist_ID" = 53, "Listens" = 0, "Song_URL" = 'eLBnWNLOAZA' WHERE "Song_ID" = 144;
UPDATE public.songs SET "Song_Name" = 'TheWeightOfLives', "Album_ID" = 99, "Artist_ID" = 53, "Listens" = 0, "Song_URL" = 'T6MfY85T2WM' WHERE "Song_ID" = 145;
UPDATE public.songs SET "Song_Name" = 'ymniam-orch', "Album_ID" = 99, "Artist_ID" = 53, "Listens" = 0, "Song_URL" = 'gwHvq1whvp0' WHERE "Song_ID" = 146;
UPDATE public.songs SET "Song_Name" = 'theDOGS', "Album_ID" = 100, "Artist_ID" = 53, "Listens" = 0, "Song_URL" = 'iW3NGzslPik' WHERE "Song_ID" = 147;
UPDATE public.songs SET "Song_Name" = 'the first town ~progressive mix', "Album_ID" = 101, "Artist_ID" = 54, "Listens" = 0, "Song_URL" = 'bFu7gH8D50c' WHERE "Song_ID" = 148;
UPDATE public.songs SET "Song_Name" = 'in the land of twilight, under the moon', "Album_ID" = 102, "Artist_ID" = 55, "Listens" = 0, "Song_URL" = 'fgJ-YljvzR0' WHERE "Song_ID" = 149;
UPDATE public.songs SET "Song_Name" = 'everytime you kissed me', "Album_ID" = 103, "Artist_ID" = 55, "Listens" = 0, "Song_URL" = 'IV6s7IKxocU' WHERE "Song_ID" = 150;
UPDATE public.songs SET "Song_Name" = 'Shut Down', "Album_ID" = 104, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'POe9SOEKotk' WHERE "Song_ID" = 151;
UPDATE public.songs SET "Song_Name" = 'Typa Girl', "Album_ID" = 104, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'UhxW9Njqqu0' WHERE "Song_ID" = 152;
UPDATE public.songs SET "Song_Name" = 'The Happiest Girl', "Album_ID" = 104, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'kVXazE8wR1Q' WHERE "Song_ID" = 153;
UPDATE public.songs SET "Song_Name" = 'Tally', "Album_ID" = 104, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'VQo4hyWfBQ4' WHERE "Song_ID" = 154;
UPDATE public.songs SET "Song_Name" = 'Hard to Love', "Album_ID" = 104, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = '7Hr3p1BHC_E' WHERE "Song_ID" = 155;
UPDATE public.songs SET "Song_Name" = 'Yeah Yeah Yeah', "Album_ID" = 104, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'wQTjv-Xo1gY' WHERE "Song_ID" = 156;
UPDATE public.songs SET "Song_Name" = 'Pink Venom', "Album_ID" = 105, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'gQlMMD8auMs' WHERE "Song_ID" = 157;
UPDATE public.songs SET "Song_Name" = 'AS IF IT''S YOUR LAST -KR ver.-', "Album_ID" = 106, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'Amq-qlqbjYA' WHERE "Song_ID" = 158;
UPDATE public.songs SET "Song_Name" = 'PLAYING WITH FIRE', "Album_ID" = 107, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = '9pdj4iJD08s' WHERE "Song_ID" = 159;
UPDATE public.songs SET "Song_Name" = 'DDU-DU DDU-DU', "Album_ID" = 108, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'IHNzOHi8sJs' WHERE "Song_ID" = 160;
UPDATE public.songs SET "Song_Name" = 'Pretty Savage', "Album_ID" = 109, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'F8c8f2nK82w' WHERE "Song_ID" = 161;
UPDATE public.songs SET "Song_Name" = 'Crazy Over You', "Album_ID" = 109, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'u7rKGj13pAs' WHERE "Song_ID" = 162;
UPDATE public.songs SET "Song_Name" = 'You Never Know', "Album_ID" = 109, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = '4Kk_iaaHd_Y' WHERE "Song_ID" = 163;
UPDATE public.songs SET "Song_Name" = 'Bet You Wanna', "Album_ID" = 109, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'gXBdvSj9F2I' WHERE "Song_ID" = 164;
UPDATE public.songs SET "Song_Name" = 'Lovesick Girls', "Album_ID" = 110, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'dyRsYk0LyA8' WHERE "Song_ID" = 165;
UPDATE public.songs SET "Song_Name" = 'Ready For Love', "Album_ID" = 111, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = '7WyHtSlvHD4' WHERE "Song_ID" = 166;
UPDATE public.songs SET "Song_Name" = 'Kick It', "Album_ID" = 112, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = '-h4QsEoPYGg' WHERE "Song_ID" = 167;
UPDATE public.songs SET "Song_Name" = 'Hope Not', "Album_ID" = 112, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'AqRQvnafWJI' WHERE "Song_ID" = 168;
UPDATE public.songs SET "Song_Name" = 'Forever Young', "Album_ID" = 113, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'tT5AkN4r3NM' WHERE "Song_ID" = 169;
UPDATE public.songs SET "Song_Name" = 'Lovesick Girls', "Album_ID" = 114, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'kLoqdvCtl9M' WHERE "Song_ID" = 170;
UPDATE public.songs SET "Song_Name" = 'DDU-DU DDU-DU', "Album_ID" = 115, "Artist_ID" = 56, "Listens" = 0, "Song_URL" = 'XiqRE2EH5y4' WHERE "Song_ID" = 171;
UPDATE public.songs SET "Song_Name" = 'Minor Feelings', "Album_ID" = 116, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'sQnzx3rEro8' WHERE "Song_ID" = 172;
UPDATE public.songs SET "Song_Name" = 'This Hell', "Album_ID" = 116, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'Klk9N84tsAI' WHERE "Song_ID" = 173;
UPDATE public.songs SET "Song_Name" = 'Catch Me In The Air', "Album_ID" = 116, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'ZW1SlN7YODQ' WHERE "Song_ID" = 174;
UPDATE public.songs SET "Song_Name" = 'Forgiveness', "Album_ID" = 116, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'TM6LwKe-JRw' WHERE "Song_ID" = 175;
UPDATE public.songs SET "Song_Name" = 'Your Age', "Album_ID" = 116, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'cKF4l1l9GJU' WHERE "Song_ID" = 176;
UPDATE public.songs SET "Song_Name" = 'Imagining', "Album_ID" = 116, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'VpbrFzU6wpM' WHERE "Song_ID" = 177;
UPDATE public.songs SET "Song_Name" = 'Frankenstein', "Album_ID" = 116, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'pLZZW4QPsuc' WHERE "Song_ID" = 178;
UPDATE public.songs SET "Song_Name" = 'Hurricanes', "Album_ID" = 116, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'uqzKejn5-a8' WHERE "Song_ID" = 179;
UPDATE public.songs SET "Song_Name" = 'Send My Love To John', "Album_ID" = 116, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'hvpPP0L5bsc' WHERE "Song_ID" = 180;
UPDATE public.songs SET "Song_Name" = 'Phantom', "Album_ID" = 116, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'Q-5melZcPj4' WHERE "Song_ID" = 181;
UPDATE public.songs SET "Song_Name" = 'To Be Alive', "Album_ID" = 116, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = '49LCxbzvmBg' WHERE "Song_ID" = 182;
UPDATE public.songs SET "Song_Name" = 'Dynasty', "Album_ID" = 117, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'AXekXn25GRs' WHERE "Song_ID" = 183;
UPDATE public.songs SET "Song_Name" = 'STFU!', "Album_ID" = 117, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'OtgyVGqMrOA' WHERE "Song_ID" = 184;
UPDATE public.songs SET "Song_Name" = 'Akasaka Sad', "Album_ID" = 117, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'XSl239RQ_mc' WHERE "Song_ID" = 185;
UPDATE public.songs SET "Song_Name" = 'Paradisin''', "Album_ID" = 117, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'G_v1BVMgJiI' WHERE "Song_ID" = 186;
UPDATE public.songs SET "Song_Name" = 'Love Me 4 Me', "Album_ID" = 117, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'jGtypOYpUMQ' WHERE "Song_ID" = 187;
UPDATE public.songs SET "Song_Name" = 'Who''s Gonna Save U Now?', "Album_ID" = 117, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'sip8XPehfdc' WHERE "Song_ID" = 188;
UPDATE public.songs SET "Song_Name" = 'Tokyo Love Hotel', "Album_ID" = 117, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = '7m8wpFC56JM' WHERE "Song_ID" = 189;
UPDATE public.songs SET "Song_Name" = 'Chosen Family', "Album_ID" = 117, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = '2nlX6qR5HGY' WHERE "Song_ID" = 190;
UPDATE public.songs SET "Song_Name" = 'Snakeskin', "Album_ID" = 117, "Artist_ID" = 57, "Listens" = 0, "Song_URL" = 'Dc2KW63YXsg' WHERE "Song_ID" = 191;
UPDATE public.songs SET "Song_Name" = 'Complicated', "Album_ID" = 118, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = '5NPBIwQyPWE' WHERE "Song_ID" = 192;
UPDATE public.songs SET "Song_Name" = 'Sk8er Boi', "Album_ID" = 118, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'TIy3n2b7V9k' WHERE "Song_ID" = 193;
UPDATE public.songs SET "Song_Name" = 'I''m With You', "Album_ID" = 118, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'dGR65RWwzg8' WHERE "Song_ID" = 194;
UPDATE public.songs SET "Song_Name" = 'Losing Grip', "Album_ID" = 118, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'LOcKckBLouM' WHERE "Song_ID" = 195;
UPDATE public.songs SET "Song_Name" = 'Mobile', "Album_ID" = 118, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'KuuhcltChKc' WHERE "Song_ID" = 196;
UPDATE public.songs SET "Song_Name" = 'Girlfriend', "Album_ID" = 119, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'Bg59q4puhmg' WHERE "Song_ID" = 197;
UPDATE public.songs SET "Song_Name" = 'What The Hell', "Album_ID" = 120, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'tQmEd_UeeIk' WHERE "Song_ID" = 198;
UPDATE public.songs SET "Song_Name" = 'Smile', "Album_ID" = 120, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'KagvExF-ijc' WHERE "Song_ID" = 199;
UPDATE public.songs SET "Song_Name" = 'Wish You Were Here', "Album_ID" = 120, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'VT1-sitWRtY' WHERE "Song_ID" = 200;
UPDATE public.songs SET "Song_Name" = 'Love It When You Hate Me', "Album_ID" = 121, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'lPi1jj12WC8' WHERE "Song_ID" = 201;
UPDATE public.songs SET "Song_Name" = 'When You''re Gone', "Album_ID" = 122, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = '0G3_kG5FFfQ' WHERE "Song_ID" = 202;
UPDATE public.songs SET "Song_Name" = 'Innocence', "Album_ID" = 122, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'hFlJZKrG2Uw' WHERE "Song_ID" = 203;
UPDATE public.songs SET "Song_Name" = 'Here''s to Never Growing Up', "Album_ID" = 123, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'sXd2WxoOP5g' WHERE "Song_ID" = 204;
UPDATE public.songs SET "Song_Name" = 'Let Me Go', "Album_ID" = 123, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'AqajUg85Ax4' WHERE "Song_ID" = 205;
UPDATE public.songs SET "Song_Name" = 'Rock N Roll', "Album_ID" = 123, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'uuNTO31FlY8' WHERE "Song_ID" = 206;
UPDATE public.songs SET "Song_Name" = 'Hello Kitty', "Album_ID" = 123, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'LiaYDPRedWQ' WHERE "Song_ID" = 207;
UPDATE public.songs SET "Song_Name" = 'Bite Me', "Album_ID" = 124, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'ciqUEV9F0OY' WHERE "Song_ID" = 208;
UPDATE public.songs SET "Song_Name" = 'My Happy Ending', "Album_ID" = 125, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 's8QYxmpuyxg' WHERE "Song_ID" = 209;
UPDATE public.songs SET "Song_Name" = 'Don''t Tell Me', "Album_ID" = 125, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'zMbIipvQL0c' WHERE "Song_ID" = 210;
UPDATE public.songs SET "Song_Name" = 'Nobody''s Home', "Album_ID" = 125, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'NGFSNE18Ywc' WHERE "Song_ID" = 211;
UPDATE public.songs SET "Song_Name" = 'He Wasn''t', "Album_ID" = 125, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'onPaBhiJxEE' WHERE "Song_ID" = 212;
UPDATE public.songs SET "Song_Name" = 'I Always Get What I Want', "Album_ID" = 125, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'nO4q2WuurZk' WHERE "Song_ID" = 213;
UPDATE public.songs SET "Song_Name" = 'Fall To Pieces', "Album_ID" = 125, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'EfcuPzCDzas' WHERE "Song_ID" = 214;
UPDATE public.songs SET "Song_Name" = 'We Are Warriors', "Album_ID" = 126, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = '3tBk7ONm95Q' WHERE "Song_ID" = 215;
UPDATE public.songs SET "Song_Name" = 'Hot', "Album_ID" = 127, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'fzb75m8NuMQ' WHERE "Song_ID" = 216;
UPDATE public.songs SET "Song_Name" = 'Bois Lie', "Album_ID" = 128, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'P82ihMcsjKw' WHERE "Song_ID" = 217;
UPDATE public.songs SET "Song_Name" = 'Alice', "Album_ID" = 129, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'YI4m-l2yRZA' WHERE "Song_ID" = 218;
UPDATE public.songs SET "Song_Name" = 'Keep Holding On', "Album_ID" = 130, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'trp6FZs2zlM' WHERE "Song_ID" = 219;
UPDATE public.songs SET "Song_Name" = 'Breakaway', "Album_ID" = 131, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'oc7JLUvY9xI' WHERE "Song_ID" = 220;
UPDATE public.songs SET "Song_Name" = 'Fly', "Album_ID" = 132, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = '7dcNG6-5O2o' WHERE "Song_ID" = 221;
UPDATE public.songs SET "Song_Name" = 'I Don''t Give', "Album_ID" = 133, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'Yxf8ODiJDrY' WHERE "Song_ID" = 222;
UPDATE public.songs SET "Song_Name" = 'Give You What You Like', "Album_ID" = 134, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'gUqL6meIfdA' WHERE "Song_ID" = 223;
UPDATE public.songs SET "Song_Name" = 'Bad Girl', "Album_ID" = 134, "Artist_ID" = 58, "Listens" = 0, "Song_URL" = 'TMIkAY_Xafk' WHERE "Song_ID" = 224;
UPDATE public.songs SET "Song_Name" = 'Bored', "Album_ID" = 135, "Artist_ID" = 59, "Listens" = 0, "Song_URL" = 'cnGW8NR-toE' WHERE "Song_ID" = 225;
UPDATE public.songs SET "Song_Name" = 'TV', "Album_ID" = 136, "Artist_ID" = 59, "Listens" = 0, "Song_URL" = '_JGGLJMpVks' WHERE "Song_ID" = 226;
UPDATE public.songs SET "Song_Name" = 'NDA', "Album_ID" = 137, "Artist_ID" = 59, "Listens" = 0, "Song_URL" = 'OORBa32WFcM' WHERE "Song_ID" = 227;
UPDATE public.songs SET "Song_Name" = 'Male Fantasy', "Album_ID" = 138, "Artist_ID" = 59, "Listens" = 0, "Song_URL" = 'G_BhUxx-cwk' WHERE "Song_ID" = 228;
UPDATE public.songs SET "Song_Name" = 'Billie Bossa Nova', "Album_ID" = 139, "Artist_ID" = 59, "Listens" = 0, "Song_URL" = '4tZ969oc-yI' WHERE "Song_ID" = 229;
UPDATE public.songs SET "Song_Name" = 'GOLDWING', "Album_ID" = 139, "Artist_ID" = 59, "Listens" = 0, "Song_URL" = 'JpL7scu-EmY' WHERE "Song_ID" = 230;
UPDATE public.songs SET "Song_Name" = 'idontwannabeyouanymore', "Album_ID" = 140, "Artist_ID" = 59, "Listens" = 0, "Song_URL" = '-tn2S3kJlyU' WHERE "Song_ID" = 231;
UPDATE public.songs SET "Song_Name" = 'COPYCAT', "Album_ID" = 141, "Artist_ID" = 59, "Listens" = 0, "Song_URL" = 'ebb5AinKxWI' WHERE "Song_ID" = 232;
UPDATE public.songs SET "Song_Name" = 'watch', "Album_ID" = 141, "Artist_ID" = 59, "Listens" = 0, "Song_URL" = '9dobJDxPEzM' WHERE "Song_ID" = 233;
UPDATE public.songs SET "Song_Name" = 'bitches broken hearts', "Album_ID" = 142, "Artist_ID" = 59, "Listens" = 0, "Song_URL" = 'qpQSjf-0Lc8' WHERE "Song_ID" = 234;
UPDATE public.songs SET "Song_Name" = 'Six Feet Under', "Album_ID" = 143, "Artist_ID" = 59, "Listens" = 0, "Song_URL" = 'FQ0iq10ULNA' WHERE "Song_ID" = 235;
UPDATE public.songs SET "Song_Name" = '8', "Album_ID" = 144, "Artist_ID" = 59, "Listens" = 0, "Song_URL" = 'OZYd9JxithE' WHERE "Song_ID" = 236;
UPDATE public.songs SET "Song_Name" = 'goodbye', "Album_ID" = 144, "Artist_ID" = 59, "Listens" = 0, "Song_URL" = 'vciZvVJyNYU' WHERE "Song_ID" = 237;
UPDATE public.songs SET "Song_Name" = 'Shinigami Eyes', "Album_ID" = 145, "Artist_ID" = 60, "Listens" = 0, "Song_URL" = 'pzPElFdxMCM' WHERE "Song_ID" = 238;
UPDATE public.songs SET "Song_Name" = 'abcdefu', "Album_ID" = 146, "Artist_ID" = 61, "Listens" = 0, "Song_URL" = 'NaFd8ucHLuo' WHERE "Song_ID" = 239;
UPDATE public.songs SET "Song_Name" = 'Valentine', "Album_ID" = 147, "Artist_ID" = 62, "Listens" = 0, "Song_URL" = 'ZxarOZ0JBcc' WHERE "Song_ID" = 240;
UPDATE public.songs SET "Song_Name" = 'Down', "Album_ID" = 148, "Artist_ID" = 63, "Listens" = 0, "Song_URL" = 'VQ9iAlm-sJ8' WHERE "Song_ID" = 241;
UPDATE public.songs SET "Song_Name" = 'The Nowhere Inn', "Album_ID" = 149, "Artist_ID" = 63, "Listens" = 0, "Song_URL" = 'z1O91hhKwYE' WHERE "Song_ID" = 242;
UPDATE public.songs SET "Song_Name" = 'Los Ageless', "Album_ID" = 150, "Artist_ID" = 63, "Listens" = 0, "Song_URL" = 'G8jxAKmojxY' WHERE "Song_ID" = 243;
UPDATE public.songs SET "Song_Name" = 'Growing Up', "Album_ID" = 151, "Artist_ID" = 64, "Listens" = 0, "Song_URL" = 'Wm1Sew7lAG4' WHERE "Song_ID" = 244;
UPDATE public.songs SET "Song_Name" = 'Clementine', "Album_ID" = 152, "Artist_ID" = 65, "Listens" = 0, "Song_URL" = 'ygbwVO1N_Eo' WHERE "Song_ID" = 245;
UPDATE public.songs SET "Song_Name" = 'Aubade', "Album_ID" = 153, "Artist_ID" = 66, "Listens" = 0, "Song_URL" = 'hSZGZx9VBzQ' WHERE "Song_ID" = 246;
UPDATE public.songs SET "Song_Name" = 'Chaise Longue', "Album_ID" = 154, "Artist_ID" = 67, "Listens" = 0, "Song_URL" = 'Zd9jeJk2UHQ' WHERE "Song_ID" = 247;
UPDATE public.songs SET "Song_Name" = 'Green Light', "Album_ID" = 155, "Artist_ID" = 68, "Listens" = 0, "Song_URL" = 'dMK_npDG12Q' WHERE "Song_ID" = 248;
UPDATE public.songs SET "Song_Name" = 'Still Into You', "Album_ID" = 156, "Artist_ID" = 69, "Listens" = 0, "Song_URL" = 'OblL026SvD4' WHERE "Song_ID" = 249;
UPDATE public.songs SET "Song_Name" = 'prom dress', "Album_ID" = 157, "Artist_ID" = 70, "Listens" = 0, "Song_URL" = 'AeUeLzBO0go' WHERE "Song_ID" = 250;
UPDATE public.songs SET "Song_Name" = 'Sofia', "Album_ID" = 158, "Artist_ID" = 71, "Listens" = 0, "Song_URL" = 'wD__jpWgWkQ' WHERE "Song_ID" = 251;
UPDATE public.songs SET "Song_Name" = 'Bags', "Album_ID" = 159, "Artist_ID" = 71, "Listens" = 0, "Song_URL" = 'L9HYJbe9Y18' WHERE "Song_ID" = 252;
UPDATE public.songs SET "Song_Name" = '1950', "Album_ID" = 160, "Artist_ID" = 72, "Listens" = 0, "Song_URL" = 'LNxWTS25Tbk' WHERE "Song_ID" = 253;
UPDATE public.songs SET "Song_Name" = 'Blood In The Cut', "Album_ID" = 161, "Artist_ID" = 73, "Listens" = 0, "Song_URL" = 'k2WcOdz96ko' WHERE "Song_ID" = 254;
UPDATE public.songs SET "Song_Name" = 'Giver', "Album_ID" = 161, "Artist_ID" = 73, "Listens" = 0, "Song_URL" = 'nt26yjdItdA' WHERE "Song_ID" = 255;
UPDATE public.songs SET "Song_Name" = 'I Said Hi', "Album_ID" = 162, "Artist_ID" = 74, "Listens" = 0, "Song_URL" = '1K4KwuV2l4s' WHERE "Song_ID" = 256;
UPDATE public.songs SET "Song_Name" = 'Mess Her Up', "Album_ID" = 162, "Artist_ID" = 74, "Listens" = 0, "Song_URL" = 'hCjcgoubkPM' WHERE "Song_ID" = 257;
UPDATE public.songs SET "Song_Name" = 'When I''m Small', "Album_ID" = 163, "Artist_ID" = 75, "Listens" = 0, "Song_URL" = '28tZ-S1LFok' WHERE "Song_ID" = 258;
UPDATE public.songs SET "Song_Name" = 'In a Spiral', "Album_ID" = 164, "Artist_ID" = 75, "Listens" = 0, "Song_URL" = 'WzGSI8XYPHs' WHERE "Song_ID" = 259;
UPDATE public.songs SET "Song_Name" = 'Dream', "Album_ID" = 165, "Artist_ID" = 76, "Listens" = 0, "Song_URL" = 'bqsiJPK-94Q' WHERE "Song_ID" = 260;
UPDATE public.songs SET "Song_Name" = 'Now I''m In It', "Album_ID" = 166, "Artist_ID" = 77, "Listens" = 0, "Song_URL" = 'G-UnzRM24IM' WHERE "Song_ID" = 261;
UPDATE public.songs SET "Song_Name" = 'Simmer', "Album_ID" = 167, "Artist_ID" = 78, "Listens" = 0, "Song_URL" = '8lSj5k2K7w0' WHERE "Song_ID" = 262;
UPDATE public.songs SET "Song_Name" = 'Seventeen', "Album_ID" = 168, "Artist_ID" = 79, "Listens" = 0, "Song_URL" = 'j7sTHoeH0eA' WHERE "Song_ID" = 263;
UPDATE public.songs SET "Song_Name" = 'Miracle', "Album_ID" = 169, "Artist_ID" = 80, "Listens" = 0, "Song_URL" = 'e1YqueG2gtQ' WHERE "Song_ID" = 264;
UPDATE public.songs SET "Song_Name" = 'Hallucinations', "Album_ID" = 170, "Artist_ID" = 81, "Listens" = 0, "Song_URL" = 'NzdUeJnn0gM' WHERE "Song_ID" = 265;
UPDATE public.songs SET "Song_Name" = 'Monday', "Album_ID" = 171, "Artist_ID" = 82, "Listens" = 0, "Song_URL" = '654WbtSEm_8' WHERE "Song_ID" = 266;
UPDATE public.songs SET "Song_Name" = 'Learn to Live', "Album_ID" = 172, "Artist_ID" = 83, "Listens" = 0, "Song_URL" = 'I51C1GtzRs4' WHERE "Song_ID" = 267;
UPDATE public.songs SET "Song_Name" = 'Smile', "Album_ID" = 173, "Artist_ID" = 84, "Listens" = 0, "Song_URL" = 'NV39h7GHDYs' WHERE "Song_ID" = 268;
UPDATE public.songs SET "Song_Name" = 'Pretty Lady', "Album_ID" = 174, "Artist_ID" = 85, "Listens" = 0, "Song_URL" = 'mj2_4T_qLLQ' WHERE "Song_ID" = 269;
UPDATE public.songs SET "Song_Name" = 'Blackbird', "Album_ID" = 175, "Artist_ID" = 85, "Listens" = 0, "Song_URL" = 'zYZeF26fO68' WHERE "Song_ID" = 270;
UPDATE public.songs SET "Song_Name" = 'please put me in a medically induced coma', "Album_ID" = 176, "Artist_ID" = 86, "Listens" = 0, "Song_URL" = 'PzUkYUWjDyA' WHERE "Song_ID" = 271;
UPDATE public.songs SET "Song_Name" = 'Fall to Pieces', "Album_ID" = 177, "Artist_ID" = 87, "Listens" = 0, "Song_URL" = 'j0tD-2C9vsw' WHERE "Song_ID" = 272;
UPDATE public.songs SET "Song_Name" = 'SUPERBLOOM', "Album_ID" = 178, "Artist_ID" = 88, "Listens" = 0, "Song_URL" = 'tv3gjE3zIIs' WHERE "Song_ID" = 273;
UPDATE public.songs SET "Song_Name" = 'Good Thing Gone', "Album_ID" = 179, "Artist_ID" = 89, "Listens" = 0, "Song_URL" = 'f9bSMmgi4i0' WHERE "Song_ID" = 274;
UPDATE public.songs SET "Song_Name" = 'Rockstar', "Album_ID" = 180, "Artist_ID" = 90, "Listens" = 0, "Song_URL" = '2l7-f-NZUDk' WHERE "Song_ID" = 275;
UPDATE public.songs SET "Song_Name" = 'Questions', "Album_ID" = 181, "Artist_ID" = 91, "Listens" = 0, "Song_URL" = 'VchylRsWmcQ' WHERE "Song_ID" = 276;
UPDATE public.songs SET "Song_Name" = 'Crying', "Album_ID" = 182, "Artist_ID" = 92, "Listens" = 0, "Song_URL" = 'pN-O-z4wpVI' WHERE "Song_ID" = 277;
UPDATE public.songs SET "Song_Name" = 'Funeral', "Album_ID" = 183, "Artist_ID" = 93, "Listens" = 0, "Song_URL" = 'X-z4-q3Xeqg' WHERE "Song_ID" = 278;
UPDATE public.songs SET "Song_Name" = 'Lovin Is Bible', "Album_ID" = 184, "Artist_ID" = 94, "Listens" = 0, "Song_URL" = 'qsy6TE8lrLQ' WHERE "Song_ID" = 279;
UPDATE public.songs SET "Song_Name" = 'Heaven', "Album_ID" = 185, "Artist_ID" = 95, "Listens" = 0, "Song_URL" = 'qbmYNpVSbUk' WHERE "Song_ID" = 280;
UPDATE public.songs SET "Song_Name" = 'One Day We''ll Make It Big', "Album_ID" = 186, "Artist_ID" = 96, "Listens" = 0, "Song_URL" = 'gd5FZZnwKoQ' WHERE "Song_ID" = 281;
UPDATE public.songs SET "Song_Name" = 'Intentions', "Album_ID" = 187, "Artist_ID" = 97, "Listens" = 0, "Song_URL" = 'bDA040TQ5Fk' WHERE "Song_ID" = 282;
UPDATE public.songs SET "Song_Name" = 'Divorce Song', "Album_ID" = 188, "Artist_ID" = 98, "Listens" = 0, "Song_URL" = 'RhGP2vTn5Tw' WHERE "Song_ID" = 283;
UPDATE public.songs SET "Song_Name" = 'Solaria / Aura', "Album_ID" = 192, "Artist_ID" = 100, "Listens" = 0, "Song_URL" = 'EKOSQGKn5Cw' WHERE "Song_ID" = 316;
UPDATE public.songs SET "Song_Name" = 'THOUGHTS AND PRAYERS', "Album_ID" = 194, "Artist_ID" = 101, "Listens" = 0, "Song_URL" = 'BZFv53IrvSg' WHERE "Song_ID" = 319;
UPDATE public.songs SET "Song_Name" = 'a_hisa - sorahana', "Album_ID" = 195, "Artist_ID" = 102, "Listens" = 0, "Song_URL" = '8S5OGyl1ejo' WHERE "Song_ID" = 320;
UPDATE public.songs SET "Song_Name" = 'Anime Thighs', "Album_ID" = 196, "Artist_ID" = 103, "Listens" = 0, "Song_URL" = '3uYIE46vJss' WHERE "Song_ID" = 322;
UPDATE public.songs SET "Song_Name" = 'Trap Anthem', "Album_ID" = 196, "Artist_ID" = 103, "Listens" = 0, "Song_URL" = 'Cg2M-7dWhoI' WHERE "Song_ID" = 324;
UPDATE public.songs SET "Song_Name" = 'Goth Bitch', "Album_ID" = 197, "Artist_ID" = 104, "Listens" = 0, "Song_URL" = 'aPgu0pfQwnQ' WHERE "Song_ID" = 325;
UPDATE public.songs SET "Song_Name" = 'Don Toliver - No Idea', "Album_ID" = 198, "Artist_ID" = 105, "Listens" = 0, "Song_URL" = '_r-nPqWGG6c' WHERE "Song_ID" = 327;
UPDATE public.songs SET "Song_Name" = 'Childish Gambino - 3005', "Album_ID" = 199, "Artist_ID" = 106, "Listens" = 0, "Song_URL" = 'tG35R8F2j8k' WHERE "Song_ID" = 328;
UPDATE public.songs SET "Song_Name" = 'Dave - Starlight', "Album_ID" = 200, "Artist_ID" = 107, "Listens" = 0, "Song_URL" = 'iVWsP3IadBk' WHERE "Song_ID" = 329;
UPDATE public.songs SET "Song_Name" = '505', "Album_ID" = 201, "Artist_ID" = 108, "Listens" = 0, "Song_URL" = 'qU9mHegkTc4' WHERE "Song_ID" = 330;
UPDATE public.songs SET "Song_Name" = 'Tek It', "Album_ID" = 202, "Artist_ID" = 109, "Listens" = 0, "Song_URL" = '6LEs1yKXnb8' WHERE "Song_ID" = 331;
UPDATE public.songs SET "Song_Name" = 'This Love', "Album_ID" = 1, "Artist_ID" = 1, "Listens" = 98, "Song_URL" = 'mvxQYPR4lmU' WHERE "Song_ID" = 3;
