UPDATE public.artists SET "Artist_Name" = 'Taylor Swift' WHERE "Artist_ID" = 1;
UPDATE public.artists SET "Artist_Name" = 'Ed Sheeran' WHERE "Artist_ID" = 2;
UPDATE public.artists SET "Artist_Name" = 'Lana Del Rey' WHERE "Artist_ID" = 3;
UPDATE public.artists SET "Artist_Name" = '3 Doors Down' WHERE "Artist_ID" = 4;
UPDATE public.artists SET "Artist_Name" = 'Linkin Park' WHERE "Artist_ID" = 5;
UPDATE public.artists SET "Artist_Name" = 'Nickelback' WHERE "Artist_ID" = 6;
UPDATE public.artists SET "Artist_Name" = 'Audioslave' WHERE "Artist_ID" = 7;
UPDATE public.artists SET "Artist_Name" = 'Evanescence' WHERE "Artist_ID" = 8;
UPDATE public.artists SET "Artist_Name" = 'The White Stripes' WHERE "Artist_ID" = 9;
UPDATE public.artists SET "Artist_Name" = 'Fall Out Boy' WHERE "Artist_ID" = 10;
UPDATE public.artists SET "Artist_Name" = 'Red Hot Chili Peppers' WHERE "Artist_ID" = 11;
UPDATE public.artists SET "Artist_Name" = 'Foo Fighters' WHERE "Artist_ID" = 12;
UPDATE public.artists SET "Artist_Name" = 'Disturbed' WHERE "Artist_ID" = 13;
UPDATE public.artists SET "Artist_Name" = 'The Offspring' WHERE "Artist_ID" = 14;
UPDATE public.artists SET "Artist_Name" = 'Staind' WHERE "Artist_ID" = 15;
UPDATE public.artists SET "Artist_Name" = 'Incubus' WHERE "Artist_ID" = 16;
UPDATE public.artists SET "Artist_Name" = 'Green Day' WHERE "Artist_ID" = 17;
UPDATE public.artists SET "Artist_Name" = 'P.O.D.' WHERE "Artist_ID" = 18;
UPDATE public.artists SET "Artist_Name" = 'Shinedown' WHERE "Artist_ID" = 19;
UPDATE public.artists SET "Artist_Name" = 'Velvet Revolver' WHERE "Artist_ID" = 20;
UPDATE public.artists SET "Artist_Name" = 'Seether' WHERE "Artist_ID" = 21;
UPDATE public.artists SET "Artist_Name" = 'Three Days Grace' WHERE "Artist_ID" = 22;
UPDATE public.artists SET "Artist_Name" = 'Bon Jovi' WHERE "Artist_ID" = 23;
UPDATE public.artists SET "Artist_Name" = 'Coldplay' WHERE "Artist_ID" = 24;
UPDATE public.artists SET "Artist_Name" = 'The Killers' WHERE "Artist_ID" = 25;
UPDATE public.artists SET "Artist_Name" = 'My Chemical Romance' WHERE "Artist_ID" = 26;
UPDATE public.artists SET "Artist_Name" = 'Muse' WHERE "Artist_ID" = 27;
UPDATE public.artists SET "Artist_Name" = 'Creed' WHERE "Artist_ID" = 28;
UPDATE public.artists SET "Artist_Name" = 'Godsmack' WHERE "Artist_ID" = 29;
UPDATE public.artists SET "Artist_Name" = 'Crazy Town' WHERE "Artist_ID" = 30;
UPDATE public.artists SET "Artist_Name" = 'U2' WHERE "Artist_ID" = 31;
UPDATE public.artists SET "Artist_Name" = 'Jet' WHERE "Artist_ID" = 32;
UPDATE public.artists SET "Artist_Name" = 'The Strokes' WHERE "Artist_ID" = 33;
UPDATE public.artists SET "Artist_Name" = 'Daughtry' WHERE "Artist_ID" = 34;
UPDATE public.artists SET "Artist_Name" = 'Breaking Benjamin' WHERE "Artist_ID" = 35;
UPDATE public.artists SET "Artist_Name" = 'Good Charlotte' WHERE "Artist_ID" = 36;
UPDATE public.artists SET "Artist_Name" = 'Stone Sour' WHERE "Artist_ID" = 37;
UPDATE public.artists SET "Artist_Name" = 'Weezer' WHERE "Artist_ID" = 38;
UPDATE public.artists SET "Artist_Name" = 'Aerosmith' WHERE "Artist_ID" = 39;
UPDATE public.artists SET "Artist_Name" = 'Yellowcard' WHERE "Artist_ID" = 40;
UPDATE public.artists SET "Artist_Name" = 'Lifehouse' WHERE "Artist_ID" = 41;
UPDATE public.artists SET "Artist_Name" = 'Ozzy Osbourne' WHERE "Artist_ID" = 42;
UPDATE public.artists SET "Artist_Name" = 'Chevelle' WHERE "Artist_ID" = 43;
UPDATE public.artists SET "Artist_Name" = 'AC/DC' WHERE "Artist_ID" = 44;
UPDATE public.artists SET "Artist_Name" = 'Metallica' WHERE "Artist_ID" = 45;
UPDATE public.artists SET "Artist_Name" = 'Jimmy Eat World' WHERE "Artist_ID" = 46;
UPDATE public.artists SET "Artist_Name" = 'Puddle of Mudd' WHERE "Artist_ID" = 47;
UPDATE public.artists SET "Artist_Name" = 'Simple Plan' WHERE "Artist_ID" = 48;
UPDATE public.artists SET "Artist_Name" = 'Our Lady Peace' WHERE "Artist_ID" = 49;
UPDATE public.artists SET "Artist_Name" = 'The Raconteurs' WHERE "Artist_ID" = 50;
UPDATE public.artists SET "Artist_Name" = 'Pearl Jam' WHERE "Artist_ID" = 51;
UPDATE public.artists SET "Artist_Name" = 'Hiroyuki Sawano' WHERE "Artist_ID" = 52;
UPDATE public.artists SET "Artist_Name" = '澤野弘之' WHERE "Artist_ID" = 53;
UPDATE public.artists SET "Artist_Name" = 'Yuki Kajiura' WHERE "Artist_ID" = 54;
UPDATE public.artists SET "Artist_Name" = '梶浦由記' WHERE "Artist_ID" = 55;
UPDATE public.artists SET "Artist_Name" = 'BLACKPINK' WHERE "Artist_ID" = 56;
UPDATE public.artists SET "Artist_Name" = 'Rina Sawayama' WHERE "Artist_ID" = 57;
UPDATE public.artists SET "Artist_Name" = 'Avril Lavigne' WHERE "Artist_ID" = 58;
UPDATE public.artists SET "Artist_Name" = 'Billie Eilish' WHERE "Artist_ID" = 59;
UPDATE public.artists SET "Artist_Name" = 'Grimes' WHERE "Artist_ID" = 60;
UPDATE public.artists SET "Artist_Name" = 'GAYLE' WHERE "Artist_ID" = 61;
UPDATE public.artists SET "Artist_Name" = 'Snail Mail' WHERE "Artist_ID" = 62;
UPDATE public.artists SET "Artist_Name" = 'St. Vincent' WHERE "Artist_ID" = 63;
UPDATE public.artists SET "Artist_Name" = 'The Linda Lindas' WHERE "Artist_ID" = 64;
UPDATE public.artists SET "Artist_Name" = 'Wet' WHERE "Artist_ID" = 65;
UPDATE public.artists SET "Artist_Name" = 'Hana Vu' WHERE "Artist_ID" = 66;
UPDATE public.artists SET "Artist_Name" = 'Wet Leg' WHERE "Artist_ID" = 67;
UPDATE public.artists SET "Artist_Name" = 'Lorde' WHERE "Artist_ID" = 68;
UPDATE public.artists SET "Artist_Name" = 'Paramore' WHERE "Artist_ID" = 69;
UPDATE public.artists SET "Artist_Name" = 'mxmtoon' WHERE "Artist_ID" = 70;
UPDATE public.artists SET "Artist_Name" = 'Clairo' WHERE "Artist_ID" = 71;
UPDATE public.artists SET "Artist_Name" = 'King Princess' WHERE "Artist_ID" = 72;
UPDATE public.artists SET "Artist_Name" = 'K.Flay' WHERE "Artist_ID" = 73;
UPDATE public.artists SET "Artist_Name" = 'Amy Shark' WHERE "Artist_ID" = 74;
UPDATE public.artists SET "Artist_Name" = 'Phantogram' WHERE "Artist_ID" = 75;
UPDATE public.artists SET "Artist_Name" = 'Bishop Briggs' WHERE "Artist_ID" = 76;
UPDATE public.artists SET "Artist_Name" = 'HAIM' WHERE "Artist_ID" = 77;
UPDATE public.artists SET "Artist_Name" = 'Hayley Williams' WHERE "Artist_ID" = 78;
UPDATE public.artists SET "Artist_Name" = 'Sharon Van Etten' WHERE "Artist_ID" = 79;
UPDATE public.artists SET "Artist_Name" = 'CHVRCHES' WHERE "Artist_ID" = 80;
UPDATE public.artists SET "Artist_Name" = 'PVRIS' WHERE "Artist_ID" = 81;
UPDATE public.artists SET "Artist_Name" = 'The Regrettes' WHERE "Artist_ID" = 82;
UPDATE public.artists SET "Artist_Name" = 'Alice Merton' WHERE "Artist_ID" = 83;
UPDATE public.artists SET "Artist_Name" = 'Wolf Alice' WHERE "Artist_ID" = 84;
UPDATE public.artists SET "Artist_Name" = 'Tash Sultana' WHERE "Artist_ID" = 85;
UPDATE public.artists SET "Artist_Name" = 'carolesdaughter' WHERE "Artist_ID" = 86;
UPDATE public.artists SET "Artist_Name" = 'Pale Waves' WHERE "Artist_ID" = 87;
UPDATE public.artists SET "Artist_Name" = 'MisterWives' WHERE "Artist_ID" = 88;
UPDATE public.artists SET "Artist_Name" = 'Elle King' WHERE "Artist_ID" = 89;
UPDATE public.artists SET "Artist_Name" = 'Mallrat' WHERE "Artist_ID" = 90;
UPDATE public.artists SET "Artist_Name" = 'Middle Kids' WHERE "Artist_ID" = 91;
UPDATE public.artists SET "Artist_Name" = 'Pom Pom Squad' WHERE "Artist_ID" = 92;
UPDATE public.artists SET "Artist_Name" = 'Meg Myers' WHERE "Artist_ID" = 93;
UPDATE public.artists SET "Artist_Name" = 'The Aces' WHERE "Artist_ID" = 94;
UPDATE public.artists SET "Artist_Name" = 'Charly Bliss' WHERE "Artist_ID" = 95;
UPDATE public.artists SET "Artist_Name" = 'Dead Sara' WHERE "Artist_ID" = 96;
UPDATE public.artists SET "Artist_Name" = 'Valeras' WHERE "Artist_ID" = 97;
UPDATE public.artists SET "Artist_Name" = 'Liz Phair' WHERE "Artist_ID" = 98;
